<?php

namespace Database\Seeders;

use App\Models\JadwalMengajar;
use App\Models\Kelas;
use App\Models\Mapel;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class JadwalMengajarSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {
            // Hapus jadwal lama agar seeder aman dijalankan ulang.
            JadwalMengajar::query()->delete();

            $normal = static function (string $value): string {
                return preg_replace('/[^a-z0-9]+/i', '', strtolower(trim($value)));
            };

            $guru = [];
            foreach (User::all() as $user) {
                $guru[$normal($user->name)] = $user->id;
            }

            $kelas = Kelas::pluck('id_kelas', 'nama_kelas')->toArray();
            $mapel = Mapel::pluck('id', 'nama_mapel')->toArray();

            $rows = [
                ['X TKI 1', 'Senin', 2, 3, 'Bahasa Inggris', 'Muto\'atul Khosi\'ah, S.Pd'],
                ['X TKI 1', 'Senin', 4, 6, 'PJOK', 'Ilham Sungeidi, S.Pd'],
                ['X TKI 1', 'Senin', 7, 8, 'Bahasa Indonesia', 'Yani, S.Pd.'],
                ['X TKI 1', 'Senin', 9, 13, 'Bahasa Jawa', 'Yustin Febrini, S.Pd'],
                ['X TKI 1', 'Selasa', 1, 2, 'Seni Budaya', 'Anang Prasetyo, S.Pd'],
                ['X TKI 1', 'Selasa', 3, 4, 'Bahasa Indonesia', 'Yani, S.Pd.'],
                ['X TKI 1', 'Selasa', 5, 7, 'IPAS', 'Khuriyatul Kamila, S.Si'],
                ['X TKI 1', 'Selasa', 8, 13, 'Dasar TKI', 'Rifkotin Na\'imah, S.Pd'],
                ['X TKI 1', 'Rabu', 1, 2, 'Koding dan Kecerdasan Artifisial', 'Endang Ary Handayani S.T., M.Pd'],
                ['X TKI 1', 'Rabu', 3, 5, 'Dasar TKI', 'Sri Kusumastuti, S.Pd'],
                ['X TKI 1', 'Rabu', 6, 8, 'Pendidikan Agama Islam dan Budi Pekerti', 'Muashofah, M.Pd'],
                ['X TKI 1', 'Rabu', 9, 13, 'Informatika', 'Lutfia Marsalina, S.Pd.I M.Pd.'],
                ['X TKI 1', 'Kamis', 1, 2, 'Matematika', 'Arvia Rienetasary, S.Pd'],
                ['X TKI 1', 'Kamis', 3, 4, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['X TKI 1', 'Kamis', 5, 7, 'IPAS', 'Khuriyatul Kamila, S.Si'],
                ['X TKI 1', 'Kamis', 8, 13, 'Dasar TKI', 'Sri Kusumastuti, S.Pd'],
                ['X TKI 1', 'Jumat', 2, 4, 'Dasar TKI', 'Rifkotin Na\'imah, S.Pd'],
                ['X TKI 1', 'Jumat', 5, 5, 'BK', 'Yuni Jiastuti S.Pd'],
                ['X TKI 1', 'Jumat', 6, 7, 'Matematika', 'Arvia Rienetasary, S.Pd'],
                ['X TKI 1', 'Jumat', 8, 9, 'Informatika', 'Lutfia Marsalina, S.Pd.I M.Pd.'],
                ['X TKI 1', 'Jumat', 10, 11, 'Sejarah', 'Fajar Luthfianto, S.Pd'],
                ['X TKI 1', 'Jumat', 12, 13, 'Bahasa Inggris', 'Muto\'atul Khosi\'ah, S.Pd'],
                ['X TKI 2', 'Senin', 2, 3, 'Bahasa Indonesia', 'Yani, S.Pd.'],
                ['X TKI 2', 'Senin', 4, 5, 'Matematika', 'Arvia Rienetasary, S.Pd'],
                ['X TKI 2', 'Senin', 6, 7, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['X TKI 2', 'Senin', 8, 13, 'Dasar TKI', 'Sri Kusumastuti, S.Pd'],
                ['X TKI 2', 'Selasa', 1, 1, 'BK', 'Yuni Jiastuti S.Pd'],
                ['X TKI 2', 'Selasa', 2, 4, 'Dasar TKI', 'Rifkotin Na\'imah, S.Pd'],
                ['X TKI 2', 'Selasa', 5, 6, 'Informatika', 'Lutfia Marsalina, S.Pd.I M.Pd.'],
                ['X TKI 2', 'Selasa', 7, 8, 'Sejarah', 'Ista Nofasari, S.Pd'],
                ['X TKI 2', 'Selasa', 9, 13, 'Koding dan Kecerdasan Artifisial', 'Endang Ary Handayani S.T., M.Pd'],
                ['X TKI 2', 'Rabu', 1, 2, 'Matematika', 'Arvia Rienetasary, S.Pd'],
                ['X TKI 2', 'Rabu', 3, 4, 'Seni Budaya', 'Anang Prasetyo, S.Pd'],
                ['X TKI 2', 'Rabu', 5, 6, 'Bahasa Inggris', 'Fitria Renytasari, S.Pd'],
                ['X TKI 2', 'Rabu', 7, 8, 'Informatika', 'Lutfia Marsalina, S.Pd.I M.Pd.'],
                ['X TKI 2', 'Rabu', 9, 13, 'Bahasa Jawa', 'Yustin Febrini, S.Pd'],
                ['X TKI 2', 'Kamis', 1, 3, 'Dasar TKI', 'Rifkotin Na\'imah, S.Pd'],
                ['X TKI 2', 'Kamis', 4, 5, 'Bahasa Inggris', 'Fitria Renytasari, S.Pd'],
                ['X TKI 2', 'Kamis', 6, 7, 'Bahasa Indonesia', 'Yani, S.Pd.'],
                ['X TKI 2', 'Kamis', 8, 13, 'IPAS', 'Khuriyatul Kamila, S.Si'],
                ['X TKI 2', 'Jumat', 2, 4, 'Pendidikan Agama Islam dan Budi Pekerti', 'Mufatiroh, S.Ag'],
                ['X TKI 2', 'Jumat', 5, 7, 'PJOK', 'Ilham Sungeidi, S.Pd'],
                ['X TKI 2', 'Jumat', 8, 10, 'Dasar TKI', 'Sri Kusumastuti, S.Pd'],
                ['X TKI 2', 'Jumat', 11, 13, 'IPAS', 'Khuriyatul Kamila, S.Si'],
                ['X RPL 1', 'Senin', 2, 3, 'Bahasa Indonesia', 'Winartin, S.Pd'],
                ['X RPL 1', 'Senin', 4, 4, 'BK', 'Widodo S.Pd'],
                ['X RPL 1', 'Senin', 5, 7, 'PJOK', 'Zainul Arifin,S.Pd'],
                ['X RPL 1', 'Senin', 8, 13, 'IPAS', 'Indriati, S.Pd'],
                ['X RPL 1', 'Selasa', 1, 3, 'IPAS', 'Indriati, S.Pd'],
                ['X RPL 1', 'Selasa', 4, 5, 'Bahasa Jawa', 'Rizki Putri Wulandari S.Pd'],
                ['X RPL 1', 'Selasa', 6, 7, 'Bahasa Inggris', 'Fitria Renytasari, S.Pd'],
                ['X RPL 1', 'Selasa', 8, 13, 'Pendidikan Agama Islam dan Budi Pekerti', 'Mufatiroh, S.Ag'],
                ['X RPL 1', 'Rabu', 1, 2, 'Seni Budaya', 'Anang Prasetyo, S.Pd'],
                ['X RPL 1', 'Rabu', 3, 4, 'Matematika', 'Elysa Yuli Nur\'aini, S.Si'],
                ['X RPL 1', 'Rabu', 5, 6, 'Informatika', 'Kurnila Putri Islamawati S.Pd'],
                ['X RPL 1', 'Rabu', 7, 13, 'Dasar PPLG', 'Badrus Sulaiman, S.Pd.'],
                ['X RPL 1', 'Kamis', 1, 2, 'Bahasa Inggris', 'Fitria Renytasari, S.Pd'],
                ['X RPL 1', 'Kamis', 3, 4, 'Matematika', 'Elysa Yuli Nur\'aini, S.Si'],
                ['X RPL 1', 'Kamis', 5, 6, 'Sejarah', 'Yustin Febrini, S.Pd'],
                ['X RPL 1', 'Kamis', 7, 13, 'Dasar PPLG', 'Ruly Dwi Setyaningrum, S.Kom'],
                ['X RPL 1', 'Jumat', 2, 5, 'Dasar PPLG', 'Ruly Dwi Setyaningrum, S.Kom'],
                ['X RPL 1', 'Jumat', 6, 7, 'Koding dan Kecerdasan Artifisial', 'Elyana Frisca Monica S.Pd'],
                ['X RPL 1', 'Jumat', 8, 9, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['X RPL 1', 'Jumat', 10, 11, 'Informatika', 'Kurnila Putri Islamawati S.Pd'],
                ['X RPL 1', 'Jumat', 12, 13, 'Bahasa Indonesia', 'Winartin, S.Pd'],
                ['X RPL 2', 'Senin', 2, 5, 'Dasar PPLG', 'Ruly Dwi Setyaningrum, S.Kom'],
                ['X RPL 2', 'Senin', 6, 7, 'Bahasa Indonesia', 'Umi Kulsum, S.Pd'],
                ['X RPL 2', 'Senin', 8, 13, 'IPAS', 'Fitri Amaliyah, S.Pd'],
                ['X RPL 2', 'Selasa', 1, 4, 'Informatika', 'Elyana Frisca Monica, S.Pd'],
                ['X RPL 2', 'Selasa', 5, 6, 'Koding dan Kecerdasan Artifisial', 'Elyana Frisca Monica S.Pd'],
                ['X RPL 2', 'Selasa', 7, 8, 'Sejarah', 'Yustin Febrini, S.Pd'],
                ['X RPL 2', 'Selasa', 9, 13, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['X RPL 2', 'Rabu', 1, 2, 'Bahasa Inggris', 'Fajar Wahyu Pratiwi, S.S'],
                ['X RPL 2', 'Rabu', 3, 4, 'Bahasa Inggris', 'Fajar Wahyu Pratiwi, S.S'],
                ['X RPL 2', 'Rabu', 5, 6, 'Matematika', 'Elysa Yuli Nur\'aini, S.Si'],
                ['X RPL 2', 'Rabu', 7, 13, 'Dasar PPLG', 'Ruly Dwi Setyaningrum, S.Kom'],
                ['X RPL 2', 'Kamis', 1, 4, 'Dasar PPLG', 'Badrus Sulaiman, S.Pd.'],
                ['X RPL 2', 'Kamis', 5, 7, 'Pendidikan Agama Islam dan Budi Pekerti', 'Mufatiroh, S.Ag'],
                ['X RPL 2', 'Kamis', 8, 13, 'IPAS', 'Fitri Amaliyah, S.Pd'],
                ['X RPL 2', 'Jumat', 2, 3, 'Bahasa Indonesia', 'Umi Kulsum, S.Pd'],
                ['X RPL 2', 'Jumat', 4, 4, 'BK', 'Widodo S.Pd'],
                ['X RPL 2', 'Jumat', 5, 7, 'PJOK', 'Zainul Arifin,S.Pd'],
                ['X RPL 2', 'Jumat', 8, 9, 'Bahasa Jawa', 'Laili Ermawati, S.Pd'],
                ['X RPL 2', 'Jumat', 10, 11, 'Seni Budaya', 'Anang Prasetyo, S.Pd'],
                ['X RPL 2', 'Jumat', 12, 13, 'Matematika', 'Elysa Yuli Nur\'aini, S.Si'],
                ['X TKJ 1', 'Senin', 2, 4, 'IPAS', 'Fitri Amaliyah, S.Pd'],
                ['X TKJ 1', 'Senin', 5, 6, 'Bahasa Inggris', 'Isti Mufadah, S.Pd'],
                ['X TKJ 1', 'Senin', 7, 8, 'Koding dan Kecerdasan Artifisial', 'Listyana Hartati, S.Kom. M.Pd'],
                ['X TKJ 1', 'Senin', 9, 13, 'Dasar TJKT', 'Listyana Hartati, S.Kom. M.Pd'],
                ['X TKJ 1', 'Selasa', 1, 4, 'Informatika', 'Siswanti Purwaningsih, S.T., M.Pd'],
                ['X TKJ 1', 'Selasa', 5, 7, 'IPAS', 'Fitri Amaliyah, S.Pd'],
                ['X TKJ 1', 'Selasa', 8, 9, 'Bahasa Jawa', 'Muhammad Fajar Assidiqi S.Pd'],
                ['X TKJ 1', 'Selasa', 10, 13, 'BK', 'Nishfu Laili S.Pd'],
                ['X TKJ 1', 'Rabu', 1, 2, 'Matematika', 'Basuki Sarjono, S.Pd'],
                ['X TKJ 1', 'Rabu', 3, 4, 'Bahasa Indonesia', 'Sri Rahayu, S.Pd'],
                ['X TKJ 1', 'Rabu', 5, 6, 'Dasar TJKT', 'Endang Ary Handayani S.T., M.Pd'],
                ['X TKJ 1', 'Rabu', 7, 8, 'Matematika', 'Basuki Sarjono, S.Pd'],
                ['X TKJ 1', 'Rabu', 9, 13, 'Bahasa Inggris', 'Isti Mufadah, S.Pd'],
                ['X TKJ 1', 'Kamis', 1, 2, 'Sejarah', 'Ista Nofasari, S.Pd'],
                ['X TKJ 1', 'Kamis', 3, 4, 'Bahasa Indonesia', 'Sri Rahayu, S.Pd'],
                ['X TKJ 1', 'Kamis', 5, 6, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['X TKJ 1', 'Kamis', 7, 13, 'Dasar TJKT', 'Siti Munawaroh, S.Kom.,M.Pd'],
                ['X TKJ 1', 'Jumat', 2, 4, 'PJOK', 'Ilham Sungeidi, S.Pd'],
                ['X TKJ 1', 'Jumat', 5, 6, 'Seni Budaya', 'Anang Prasetyo, S.Pd'],
                ['X TKJ 1', 'Jumat', 7, 10, 'Dasar TJKT', 'Siswanti Purwaningsih, S.T., M.Pd'],
                ['X TKJ 1', 'Jumat', 11, 13, 'Pendidikan Agama Islam dan Budi Pekerti', 'Sinta Lestari, S.Pd.I'],
                ['X TKJ 2', 'Senin', 2, 5, 'Dasar TJKT', 'Siti Munawaroh, S.Kom.,M.Pd'],
                ['X TKJ 2', 'Senin', 6, 8, 'Pendidikan Agama Islam dan Budi Pekerti', 'Sinta Lestari, S.Pd.I'],
                ['X TKJ 2', 'Senin', 9, 13, 'Matematika', 'Basuki Sarjono, S.Pd'],
                ['X TKJ 2', 'Selasa', 1, 2, 'Bahasa Indonesia', 'Sri Rahayu, S.Pd'],
                ['X TKJ 2', 'Selasa', 3, 5, 'PJOK', 'Ilham Sungeidi, S.Pd'],
                ['X TKJ 2', 'Selasa', 6, 7, 'Dasar TJKT', 'Endang Ary Handayani S.T., M.Pd'],
                ['X TKJ 2', 'Selasa', 8, 13, 'IPAS', 'Fitri Amaliyah, S.Pd'],
                ['X TKJ 2', 'Rabu', 1, 2, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['X TKJ 2', 'Rabu', 3, 3, 'BK', 'Nishfu Laili, S.Pd'],
                ['X TKJ 2', 'Rabu', 4, 6, 'IPAS', 'Fitri Amaliyah, S.Pd'],
                ['X TKJ 2', 'Rabu', 7, 8, 'Dasar TJKT', 'Listyana Hartati, S.Kom. M.Pd'],
                ['X TKJ 2', 'Rabu', 9, 13, 'Matematika', 'Basuki Sarjono, S.Pd'],
                ['X TKJ 2', 'Kamis', 1, 4, 'Informatika', 'Siswanti Purwaningsih, S.T., M.Pd'],
                ['X TKJ 2', 'Kamis', 5, 6, 'Bahasa Indonesia', 'Sri Rahayu, S.Pd'],
                ['X TKJ 2', 'Kamis', 7, 8, 'Seni Budaya', 'Anang Prasetyo, S.Pd'],
                ['X TKJ 2', 'Kamis', 9, 13, 'Bahasa Inggris', 'Isti Mufadah, S.Pd'],
                ['X TKJ 2', 'Jumat', 2, 5, 'Dasar TJKT', 'Siswanti Purwaningsih, S.T., M.Pd'],
                ['X TKJ 2', 'Jumat', 6, 7, 'Sejarah', 'Yustin Febrini, S.Pd'],
                ['X TKJ 2', 'Jumat', 8, 9, 'Bahasa Jawa', 'Muhammad Fajar Assidiqi S.Pd'],
                ['X TKJ 2', 'Jumat', 10, 11, 'Bahasa Inggris', 'Isti Mufadah, S.Pd'],
                ['X TKJ 2', 'Jumat', 12, 13, 'Koding dan Kecerdasan Artifisial', 'Listyana Hartati, S.Kom. M.Pd'],
                ['X BD 1', 'Senin', 2, 3, 'Sejarah', 'Pipit Ambarwati, S.Pd'],
                ['X BD 1', 'Senin', 4, 7, 'Dasar PM', 'Ratih Dian Irawati, SE'],
                ['X BD 1', 'Senin', 8, 9, 'Bahasa Indonesia', 'Arif Setyobudi, S.Pd'],
                ['X BD 1', 'Senin', 10, 13, 'BK', 'Dian Mawarti S.Pd'],
                ['X BD 1', 'Selasa', 1, 3, 'Pendidikan Agama Islam dan Budi Pekerti', 'Sinta Lestari, S.Pd.I'],
                ['X BD 1', 'Selasa', 4, 5, 'Bahasa Indonesia', 'Arif Setyobudi, S.Pd'],
                ['X BD 1', 'Selasa', 6, 8, 'IPAS', 'Indriati, S.Pd'],
                ['X BD 1', 'Selasa', 9, 13, 'Matematika', 'Laili Ermawati, S.Pd'],
                ['X BD 1', 'Rabu', 1, 2, 'Koding dan Kecerdasan Artifisial', 'Siti Munawaroh, S.Kom. M.Pd'],
                ['X BD 1', 'Rabu', 3, 4, 'Bahasa Inggris', 'Muto\'atul Khosi\'ah, S.Pd'],
                ['X BD 1', 'Rabu', 5, 8, 'Dasar PM', 'Anisa Kusumawati, S.Pd'],
                ['X BD 1', 'Rabu', 9, 13, 'Seni Budaya', 'Angga Widhy Wirawan S.Pd.,M.Pd'],
                ['X BD 1', 'Kamis', 1, 3, 'IPAS', 'Indriati, S.Pd'],
                ['X BD 1', 'Kamis', 4, 6, 'PJOK', 'Agus Fahruddy, S.Pd., M.Pd'],
                ['X BD 1', 'Kamis', 7, 8, 'Bahasa Inggris', 'Muto\'atul Khosi\'ah, S.Pd'],
                ['X BD 1', 'Kamis', 9, 13, 'Pendidikan Pancasila', 'Anisa Kusumawati, S.Pd'],
                ['X BD 1', 'Jumat', 2, 5, 'Informatika', 'Eko Saputro, S.Pd'],
                ['X BD 1', 'Jumat', 6, 7, 'Matematika', 'Laili Ermawati, S.Pd'],
                ['X BD 1', 'Jumat', 8, 11, 'Dasar PM', 'Retno Widyastuti, S.Pd., M.Pd'],
                ['X BD 1', 'Jumat', 12, 13, 'Bahasa Jawa', 'Rizki Putri Wulandari S.Pd'],
                ['X BD 2', 'Senin', 2, 4, 'IPAS', 'Indriati, S.Pd'],
                ['X BD 2', 'Senin', 5, 8, 'Dasar PM', 'Retno Widyastuti, S.Pd., M.Pd'],
                ['X BD 2', 'Senin', 9, 13, 'Pendidikan Pancasila', 'Anisa Kusumawati, S.Pd'],
                ['X BD 2', 'Selasa', 1, 2, 'Bahasa Jawa', 'Erna Qoriah, S.E.'],
                ['X BD 2', 'Selasa', 3, 4, 'Koding dan Kecerdasan Artifisial', 'Siti Munawaroh, S.Kom. M.Pd'],
                ['X BD 2', 'Selasa', 5, 6, 'Matematika', 'Laili Ermawati, S.Pd'],
                ['X BD 2', 'Selasa', 7, 13, 'Dasar PM', 'Ratih Dian Irawati, SE'],
                ['X BD 2', 'Rabu', 1, 3, 'Pendidikan Agama Islam dan Budi Pekerti', 'Sinta Lestari, S.Pd.I'],
                ['X BD 2', 'Rabu', 4, 6, 'IPAS', 'Indriati, S.Pd'],
                ['X BD 2', 'Rabu', 7, 13, 'Informatika', 'Eko Saputro, S.Pd'],
                ['X BD 2', 'Kamis', 1, 4, 'Dasar PM', 'Anisa Kusumawati, S.Pd'],
                ['X BD 2', 'Kamis', 5, 6, 'Bahasa Inggris', 'Dwi Rini Manfaati, S.Pd'],
                ['X BD 2', 'Kamis', 7, 8, 'Sejarah', 'Pipit Ambarwati, S.Pd'],
                ['X BD 2', 'Kamis', 9, 13, 'Bahasa Indonesia', 'Arif Setyobudi, S.Pd'],
                ['X BD 2', 'Jumat', 2, 2, 'BK', 'Dian Mawarti S.Pd'],
                ['X BD 2', 'Jumat', 3, 4, 'Bahasa Inggris', 'Dwi Rini Manfaati, S.Pd'],
                ['X BD 2', 'Jumat', 5, 7, 'PJOK', 'Agus Fahruddy, S.Pd., M.Pd'],
                ['X BD 2', 'Jumat', 8, 9, 'Bahasa Indonesia', 'Arif Setyobudi, S.Pd'],
                ['X BD 2', 'Jumat', 10, 11, 'Seni Budaya', 'Angga Widhy Wirawan S.Pd.,M.Pd'],
                ['X BD 2', 'Jumat', 12, 13, 'Matematika', 'Laili Ermawati, S.Pd'],
                ['X BD 3', 'Senin', 2, 4, 'Pendidikan Agama Islam dan Budi Pekerti', 'Fitria Diah Ayu Hartati, S.Pd'],
                ['X BD 3', 'Senin', 5, 7, 'PJOK', 'Bella Prakoso, S.Pd'],
                ['X BD 3', 'Senin', 8, 13, 'IPAS', 'Sri Subekti, S.Pd'],
                ['X BD 3', 'Selasa', 1, 2, 'Matematika', 'Eko Saputro, S.Pd'],
                ['X BD 3', 'Selasa', 3, 6, 'Dasar PM', 'Retno Widyastuti, S.Pd., M.Pd'],
                ['X BD 3', 'Selasa', 7, 8, 'Bahasa Inggris', 'Dwi Rini Manfaati, S.Pd'],
                ['X BD 3', 'Selasa', 9, 13, 'Bahasa Indonesia', 'Siti Khoiriyah, S.Pd'],
                ['X BD 3', 'Rabu', 1, 4, 'Dasar PM', 'Anisa Kusumawati, S.Pd'],
                ['X BD 3', 'Rabu', 5, 6, 'Sejarah', 'Yustin Febrini, S.Pd'],
                ['X BD 3', 'Rabu', 7, 8, 'Bahasa Jawa', 'Muhammad Fajar Assidiqi S.Pd'],
                ['X BD 3', 'Rabu', 9, 13, 'Bahasa Indonesia', 'Siti Khoiriyah, S.Pd'],
                ['X BD 3', 'Kamis', 1, 2, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['X BD 3', 'Kamis', 3, 5, 'IPAS', 'Sri Subekti, S.Pd'],
                ['X BD 3', 'Kamis', 6, 7, 'Seni Budaya', 'Angga Widhy Wirawan S.Pd.,M.Pd'],
                ['X BD 3', 'Kamis', 8, 9, 'Bahasa Inggris', 'Dwi Rini Manfaati, S.Pd'],
                ['X BD 3', 'Kamis', 10, 13, 'BK', 'Niken Hari Pratiwi, S.Psi.,M.Pd'],
                ['X BD 3', 'Jumat', 2, 5, 'Dasar PM', 'Ratih Dian Irawati, SE'],
                ['X BD 3', 'Jumat', 6, 9, 'Informatika', 'Eko Saputro, S.Pd'],
                ['X BD 3', 'Jumat', 10, 11, 'Matematika', 'Eko Saputro, S.Pd'],
                ['X BD 3', 'Jumat', 12, 13, 'Koding dan Kecerdasan Artifisial', 'Siti Munawaroh, S.Kom. M.Pd'],
                ['X MP 1', 'Senin', 2, 4, 'IPAS', 'Sri Subekti, S.Pd'],
                ['X MP 1', 'Senin', 5, 6, 'Sejarah', 'Fajar Luthfianto, S.Pd'],
                ['X MP 1', 'Senin', 7, 8, 'Seni Budaya', 'Angga Widhy Wirawan S.Pd.,M.Pd'],
                ['X MP 1', 'Senin', 9, 13, 'Bahasa Indonesia', 'Purwati,S.Pd'],
                ['X MP 1', 'Selasa', 1, 4, 'Dasar MPLB', 'Dwi Kuswanto, S.Pd'],
                ['X MP 1', 'Selasa', 5, 6, 'Bahasa Inggris', 'Komariyah, S.Pd'],
                ['X MP 1', 'Selasa', 7, 8, 'Bahasa Indonesia', 'Purwati,S.Pd'],
                ['X MP 1', 'Selasa', 9, 13, 'Matematika', 'Rulik Indrawati, S.Pd'],
                ['X MP 1', 'Rabu', 1, 2, 'Bahasa Inggris', 'Komariyah, S.Pd'],
                ['X MP 1', 'Rabu', 3, 4, 'Bahasa Jawa', 'Muhammad Fajar Assidiqi S.Pd'],
                ['X MP 1', 'Rabu', 5, 7, 'IPAS', 'Sri Subekti, S.Pd'],
                ['X MP 1', 'Rabu', 8, 8, 'BK', 'Veronica Damay Rulitasari S.Pd'],
                ['X MP 1', 'Rabu', 9, 13, 'Informatika', 'Kurnila Putri Islamawati S.Pd'],
                ['X MP 1', 'Kamis', 1, 2, 'Pendidikan Pancasila', 'Tutut Sriatin, S.Pd'],
                ['X MP 1', 'Kamis', 3, 4, 'Matematika', 'Rulik Indrawati, S.Pd'],
                ['X MP 1', 'Kamis', 5, 6, 'Koding dan Kecerdasan Artifisial', 'Kurnila Putri Islamawati S.Pd'],
                ['X MP 1', 'Kamis', 7, 13, 'Dasar MPLB', 'Dwi Kuswanto, S.Pd'],
                ['X MP 1', 'Jumat', 2, 4, 'PJOK', 'Zainul Arifin,S.Pd'],
                ['X MP 1', 'Jumat', 5, 8, 'Dasar MPLB', 'Dwi Kuswanto, S.Pd'],
                ['X MP 1', 'Jumat', 9, 11, 'Pendidikan Agama Islam dan Budi Pekerti', 'Fitria Diah Ayu Hartati, S.Pd'],
                ['X MP 1', 'Jumat', 12, 13, 'Informatika', 'Kurnila Putri Islamawati S.Pd'],
                ['X MP 2', 'Senin', 2, 2, 'BK', 'Nishfu Laili S.Pd'],
                ['X MP 2', 'Senin', 3, 4, 'Pendidikan Pancasila', 'Tutut Sriatin, S.Pd'],
                ['X MP 2', 'Senin', 5, 6, 'Bahasa Jawa', 'Muhammad Fajar Assidiqi S.Pd'],
                ['X MP 2', 'Senin', 7, 8, 'Bahasa Inggris', 'Komariyah, S.Pd'],
                ['X MP 2', 'Senin', 9, 13, 'Sejarah', 'Fajar Luthfianto, S.Pd'],
                ['X MP 2', 'Selasa', 1, 2, 'Bahasa Inggris', 'Komariyah, S.Pd'],
                ['X MP 2', 'Selasa', 3, 4, 'Matematika', 'Rulik Indrawati, S.Pd'],
                ['X MP 2', 'Selasa', 5, 8, 'Dasar MPLB', 'Peni Wulandari, S.Pd'],
                ['X MP 2', 'Selasa', 9, 13, 'Koding dan Kecerdasan Artifisial', 'Kurnila Putri Islamawati S.Pd'],
                ['X MP 2', 'Rabu', 1, 2, 'Seni Budaya', 'Angga Widhy Wirawan S.Pd.,M.Pd'],
                ['X MP 2', 'Rabu', 3, 5, 'PJOK', 'Zainul Arifin,S.Pd'],
                ['X MP 2', 'Rabu', 6, 7, 'Matematika', 'Rulik Indrawati, S.Pd'],
                ['X MP 2', 'Rabu', 8, 13, 'IPAS', 'Sri Subekti, S.Pd'],
                ['X MP 2', 'Kamis', 1, 4, 'Informatika', 'Ary Sunaryo, ST.,M.Pd'],
                ['X MP 2', 'Kamis', 5, 6, 'Bahasa Indonesia', 'Purwati,S.Pd'],
                ['X MP 2', 'Kamis', 7, 13, 'Dasar MPLB', 'Peni Wulandari, S.Pd'],
                ['X MP 2', 'Jumat', 2, 4, 'IPAS', 'Sri Subekti, S.Pd'],
                ['X MP 2', 'Jumat', 5, 7, 'Pendidikan Agama Islam dan Budi Pekerti', 'Fitria Diah Ayu Hartati, S.Pd'],
                ['X MP 2', 'Jumat', 8, 9, 'Bahasa Indonesia', 'Purwati,S.Pd'],
                ['X MP 2', 'Jumat', 10, 13, 'Dasar MPLB', 'Peni Wulandari, S.Pd'],
                ['X MP 3', 'Senin', 2, 4, 'PJOK', 'Zainul Arifin,S.Pd'],
                ['X MP 3', 'Senin', 5, 6, 'Bahasa Inggris', 'Komariyah, S.Pd'],
                ['X MP 3', 'Senin', 7, 13, 'Dasar MPLB', 'Lilik Suratmi, S.Pd'],
                ['X MP 3', 'Selasa', 1, 2, 'Bahasa Indonesia', 'Arif Setyobudi, S.Pd'],
                ['X MP 3', 'Selasa', 3, 4, 'Bahasa Inggris', 'Komariyah, S.Pd'],
                ['X MP 3', 'Selasa', 5, 6, 'Koding dan Kecerdasan Artifisial', 'Badrus Sulaiman, S.Pd.'],
                ['X MP 3', 'Selasa', 7, 13, 'Dasar MPLB', 'Lilik Suratmi, S.Pd'],
                ['X MP 3', 'Rabu', 1, 2, 'Bahasa Indonesia', 'Arif Setyobudi, S.Pd'],
                ['X MP 3', 'Rabu', 3, 4, 'Matematika', 'Basuki Sarjono, S.Pd'],
                ['X MP 3', 'Rabu', 5, 7, 'IPAS', 'Khuriyatul Kamila, S.Si'],
                ['X MP 3', 'Rabu', 8, 13, 'Pendidikan Agama Islam dan Budi Pekerti', 'Fitria Diah Ayu Hartati, S.Pd'],
                ['X MP 3', 'Kamis', 1, 3, 'IPAS', 'Khuriyatul Kamila, S.Si'],
                ['X MP 3', 'Kamis', 4, 5, 'Matematika', 'Basuki Sarjono, S.Pd'],
                ['X MP 3', 'Kamis', 6, 6, 'BK', 'Nur Eko Wahyuningsi h, S.Pd'],
                ['X MP 3', 'Kamis', 7, 13, 'Informatika', 'Badrus Sulaiman, S.Pd.'],
                ['X MP 3', 'Jumat', 2, 3, 'Pendidikan Pancasila', 'Khuriyatul Kamila, S.Si'],
                ['X MP 3', 'Jumat', 4, 5, 'Sejarah', 'Yustin Febrini, S.Pd'],
                ['X MP 3', 'Jumat', 6, 7, 'Bahasa Jawa', 'Rizki Putri Wulandari S.Pd'],
                ['X MP 3', 'Jumat', 8, 11, 'Dasar MPLB', 'Lilik Suratmi, S.Pd'],
                ['X MP 3', 'Jumat', 12, 13, 'Seni Budaya', 'Angga Widhy Wirawan S.Pd.,M.Pd'],
                ['X MP 4', 'Senin', 2, 4, 'IPAS', 'Khuriyatul Kamila, S.Si'],
                ['X MP 4', 'Senin', 5, 8, 'Dasar MPLB', 'Rindang Rejeki, S.Pd'],
                ['X MP 4', 'Senin', 9, 13, 'Matematika', 'Eko Saputro, S.Pd'],
                ['X MP 4', 'Selasa', 1, 3, 'PJOK', 'Zainul Arifin,S.Pd'],
                ['X MP 4', 'Selasa', 4, 5, 'Bahasa Inggris', 'Muto\'atul Khosi\'ah, S.Pd'],
                ['X MP 4', 'Selasa', 6, 7, 'Bahasa Indonesia', 'Arif Setyobudi, S.Pd'],
                ['X MP 4', 'Selasa', 8, 13, 'IPAS', 'Khuriyatul Kamila, S.Si'],
                ['X MP 4', 'Rabu', 1, 2, 'Koding dan Kecerdasan Artifisial', 'Badrus Sulaiman, S.Pd.'],
                ['X MP 4', 'Rabu', 3, 6, 'Dasar MPLB', 'Rindang Rejeki, S.Pd'],
                ['X MP 4', 'Rabu', 7, 8, 'Bahasa Indonesia', 'Arif Setyobudi, S.Pd'],
                ['X MP 4', 'Rabu', 9, 13, 'Sejarah', 'Fajar Luthfianto, S.Pd'],
                ['X MP 4', 'Kamis', 1, 2, 'Bahasa Inggris', 'Muto\'atul Khosi\'ah, S.Pd'],
                ['X MP 4', 'Kamis', 3, 3, 'BK', 'Siti Maisaroh S.Pd'],
                ['X MP 4', 'Kamis', 4, 6, 'Pendidikan Agama Islam dan Budi Pekerti', 'Alfinu Farikh Abdillah, S.Pd.I'],
                ['X MP 4', 'Kamis', 7, 8, 'Matematika', 'Eko Saputro, S.Pd'],
                ['X MP 4', 'Kamis', 9, 13, 'Seni Budaya', 'Angga Widhy Wirawan S.Pd.,M.Pd'],
                ['X MP 4', 'Jumat', 2, 5, 'Informatika', 'Badrus Sulaiman, S.Pd.'],
                ['X MP 4', 'Jumat', 6, 7, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['X MP 4', 'Jumat', 8, 9, 'Bahasa Jawa', 'Rizki Putri Wulandari S.Pd'],
                ['X MP 4', 'Jumat', 10, 13, 'Dasar MPLB', 'Rindang Rejeki, S.Pd'],
                ['X AK 1', 'Senin', 2, 3, 'Matematika', 'Lutfia Marsalina, S.Pd.I M.Pd.'],
                ['X AK 1', 'Senin', 4, 5, 'Bahasa Inggris', 'Fitria Renytasari, S.Pd'],
                ['X AK 1', 'Senin', 6, 6, 'BK', 'Nur Eko Wahyuningsi h, S.Pd'],
                ['X AK 1', 'Senin', 7, 8, 'Sejarah', 'Fajar Luthfianto, S.Pd'],
                ['X AK 1', 'Senin', 9, 13, 'Informatika', 'Shinta Indyar Shanty Susanto, S.Kom'],
                ['X AK 1', 'Selasa', 1, 2, 'Seni Budaya', 'Angga Widhy Wirawan, S.Pd.,M.Pd'],
                ['X AK 1', 'Selasa', 3, 5, 'Dasar AKL', 'Pipit Ambarwati, S.Pd'],
                ['X AK 1', 'Selasa', 6, 8, 'IPAS', 'Sri Subekti, S.Pd'],
                ['X AK 1', 'Selasa', 9, 13, 'Informatika', 'Shinta Indyar Shanty Susanto, S.Kom'],
                ['X AK 1', 'Rabu', 1, 2, 'Bahasa Inggris', 'Fitria Renytasari, S.Pd'],
                ['X AK 1', 'Rabu', 3, 5, 'PJOK', 'Agus Fahruddy, S.Pd., M.Pd'],
                ['X AK 1', 'Rabu', 6, 7, 'Bahasa Indonesia', 'Endang Safitri, S.Pd'],
                ['X AK 1', 'Rabu', 8, 13, 'Dasar AKL', 'Pipit Ambarwati, S.Pd'],
                ['X AK 1', 'Kamis', 1, 2, 'Bahasa Indonesia', 'Endang Safitri, S.Pd'],
                ['X AK 1', 'Kamis', 3, 4, 'Bahasa Jawa', 'Fitri Amaliyah, S.Pd'],
                ['X AK 1', 'Kamis', 5, 6, 'Dasar AKL', 'Atih Wilupi, S.E, M.Pd'],
                ['X AK 1', 'Kamis', 7, 8, 'Pendidikan Pancasila', 'Yuli Ratnasari, S.Pd'],
                ['X AK 1', 'Kamis', 9, 13, 'Matematika', 'Lutfia Marsalina, S.Pd.I, M.Pd.'],
                ['X AK 1', 'Jumat', 2, 3, 'Koding dan Kecerdasan Artifisial', 'Shinta Indyar Shanty Susanto, S.Kom'],
                ['X AK 1', 'Jumat', 4, 6, 'Pendidikan Agama Islam dan Budi Pekerti', 'Alfinu Farikh Abdillah, S.Pd.I'],
                ['X AK 1', 'Jumat', 7, 9, 'IPAS', 'Sri Subekti, S.Pd'],
                ['X AK 1', 'Jumat', 10, 13, 'Dasar AKL', 'Agustina Mardika Rini, S.Pd.,M.Pd'],
                ['X AK 2', 'Senin', 2, 3, 'Bahasa Inggris', 'Fitria Renytasari, S.Pd'],
                ['X AK 2', 'Senin', 4, 6, 'Dasar AKL', 'Indayah, S.Pd., M.Pd'],
                ['X AK 2', 'Senin', 7, 8, 'Informatika', 'Shinta Indyar Shanty Susanto, S.Kom'],
                ['X AK 2', 'Senin', 9, 13, 'Bahasa Indonesia', 'Endang Safitri, S.Pd'],
                ['X AK 2', 'Selasa', 1, 2, 'Informatika', 'Shinta Indyar Shanty Susanto, S.Kom'],
                ['X AK 2', 'Selasa', 3, 4, 'Bahasa Inggris', 'Fitria Renytasari, S.Pd'],
                ['X AK 2', 'Selasa', 5, 7, 'PJOK', 'Agus Fahruddy, S.Pd., M.Pd'],
                ['X AK 2', 'Selasa', 8, 9, 'Matematika', 'Lutfia Marsalina, S.Pd.I, M.Pd.'],
                ['X AK 2', 'Selasa', 10, 13, 'BK', 'Nur Eko Wahyuningsi h, S.Pd'],
                ['X AK 2', 'Rabu', 1, 3, 'IPAS', 'Sri Subekti, S.Pd'],
                ['X AK 2', 'Rabu', 4, 6, 'Pendidikan Agama Islam dan Budi Pekerti', 'Alfinu Farikh Abdillah, S.Pd.I'],
                ['X AK 2', 'Rabu', 7, 13, 'Dasar AKL', 'Agustina Mardika Rini, S.Pd.,M.Pd'],
                ['X AK 2', 'Kamis', 1, 3, 'Dasar AKL', 'Indayah, S.Pd., M.Pd'],
                ['X AK 2', 'Kamis', 4, 5, 'Matematika', 'Lutfia Marsalina, S.Pd.I, M.Pd.'],
                ['X AK 2', 'Kamis', 6, 8, 'IPAS', 'Sri Subekti, S.Pd'],
                ['X AK 2', 'Kamis', 9, 13, 'Koding dan Kecerdasan Artifisial', 'Shinta Indyar Shanty Susanto, S.Kom'],
                ['X AK 2', 'Jumat', 2, 3, 'Pendidikan Pancasila', 'Yuli Ratnasari, S.Pd'],
                ['X AK 2', 'Jumat', 4, 5, 'Bahasa Indonesia', 'Endang Safitri, S.Pd'],
                ['X AK 2', 'Jumat', 6, 7, 'Bahasa Jawa', 'Fitri Amaliyah, S.Pd'],
                ['X AK 2', 'Jumat', 8, 9, 'Seni Budaya', 'Angga Widhy Wirawan, S.Pd.,M.Pd'],
                ['X AK 2', 'Jumat', 10, 11, 'Dasar AKL', 'Pipit Ambarwati, S.Pd'],
                ['X AK 2', 'Jumat', 12, 13, 'Sejarah', 'Fajar Luthfianto, S.Pd'],
                ['X AK 3', 'Senin', 2, 4, 'PJOK', 'Agus Fahruddy, S.Pd., M.Pd'],
                ['X AK 3', 'Senin', 5, 6, 'Dasar AKL', 'Pipit Ambarwati, S.Pd'],
                ['X AK 3', 'Senin', 7, 8, 'Koding dan Kecerdasan Artifisial', 'Ruly Dwi Setyaningrum S.Kom'],
                ['X AK 3', 'Senin', 9, 13, 'Informatika', 'Ary Sunaryo, ST.,M.Pd'],
                ['X AK 3', 'Selasa', 1, 2, 'Informatika', 'Ary Sunaryo, ST.,M.Pd'],
                ['X AK 3', 'Selasa', 3, 4, 'Seni Budaya', 'Angga Widhy Wirawan, S.Pd.,M.Pd'],
                ['X AK 3', 'Selasa', 5, 6, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['X AK 3', 'Selasa', 7, 8, 'Bahasa Indonesia', 'Endang Safitri, S.Pd'],
                ['X AK 3', 'Selasa', 9, 13, 'Bahasa Inggris', 'Andri Retno Yuli Astuti, S.Pd'],
                ['X AK 3', 'Rabu', 1, 3, 'Pendidikan Agama Islam dan Budi Pekerti', 'Alfinu Farikh Abdillah, S.Pd.I'],
                ['X AK 3', 'Rabu', 4, 5, 'Matematika', 'Dwi Nova Setyandari, S.Pd'],
                ['X AK 3', 'Rabu', 6, 6, 'BK', 'Astra Bella Flamboyan, S.Psi'],
                ['X AK 3', 'Rabu', 7, 13, 'Dasar AKL', 'Titin Sukmasari, S.Pd., M.Pd'],
                ['X AK 3', 'Kamis', 1, 2, 'Sejarah', 'Pipit Ambarwati, S.Pd'],
                ['X AK 3', 'Kamis', 3, 4, 'Bahasa Jawa', 'Rizki Putri Wulandari, S.Pd'],
                ['X AK 3', 'Kamis', 5, 7, 'Dasar AKL', 'Setiyo Winarko, S.Pd'],
                ['X AK 3', 'Kamis', 8, 13, 'IPAS', 'Ista Nofasari, S.Pd'],
                ['X AK 3', 'Jumat', 2, 4, 'IPAS', 'Ista Nofasari, S.Pd'],
                ['X AK 3', 'Jumat', 5, 6, 'Bahasa Inggris', 'Andri Retno Yuli Astuti, S.Pd'],
                ['X AK 3', 'Jumat', 7, 9, 'Dasar AKL', 'Setiyo Winarko, S.Pd'],
                ['X AK 3', 'Jumat', 10, 11, 'Matematika', 'Dwi Nova Setyandari S.Pd'],
                ['X AK 3', 'Jumat', 12, 13, 'Bahasa Indonesia', 'Endang Safitri, S.Pd'],
                ['X AK 4', 'Senin', 2, 3, 'Seni Budaya', 'Angga Widhy Wirawan, S.Pd.,M.Pd'],
                ['X AK 4', 'Senin', 4, 4, 'BK', 'Astra Bella Flamboyan, S.Psi'],
                ['X AK 4', 'Senin', 5, 7, 'IPAS', 'Ista Nofasari, S.Pd'],
                ['X AK 4', 'Senin', 8, 13, 'Pendidikan Agama Islam dan Budi Pekerti', 'Muashofah, M.Pd'],
                ['X AK 4', 'Selasa', 1, 2, 'Sejarah', 'Pipit Ambarwati, S.Pd'],
                ['X AK 4', 'Selasa', 3, 4, 'Informatika', 'Ary Sunaryo, ST.,M.Pd'],
                ['X AK 4', 'Selasa', 5, 6, 'Matematika', 'Dwi Nova Setyandari, S.Pd'],
                ['X AK 4', 'Selasa', 7, 8, 'Bahasa Inggris', 'Andri Retno Yuli Astuti, S.Pd'],
                ['X AK 4', 'Selasa', 9, 13, 'Dasar AKL', 'Pipit Ambarwati, S.Pd'],
                ['X AK 4', 'Rabu', 1, 3, 'Dasar AKL', 'Septiani, S.Pd.,M.Pd'],
                ['X AK 4', 'Rabu', 4, 5, 'Bahasa Jawa', 'Rizki Putri Wulandari, S.Pd'],
                ['X AK 4', 'Rabu', 6, 7, 'Bahasa Indonesia', 'Siti Khoiriyah, S.Pd'],
                ['X AK 4', 'Rabu', 8, 13, 'IPAS', 'Ista Nofasari, S.Pd'],
                ['X AK 4', 'Kamis', 1, 3, 'PJOK', 'Agus Fahruddy, S.Pd., M.Pd'],
                ['X AK 4', 'Kamis', 4, 6, 'Dasar AKL', 'Septiani, S.Pd.,M.Pd'],
                ['X AK 4', 'Kamis', 7, 8, 'Bahasa Inggris', 'Andri Retno Yuli Astuti, S.Pd'],
                ['X AK 4', 'Kamis', 9, 13, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['X AK 4', 'Jumat', 2, 3, 'Informatika', 'Ary Sunaryo, ST.,M.Pd'],
                ['X AK 4', 'Jumat', 4, 5, 'Matematika', 'Dwi Nova Setyandari, S.Pd'],
                ['X AK 4', 'Jumat', 6, 7, 'Bahasa Indonesia', 'Siti Khoiriyah, S.Pd'],
                ['X AK 4', 'Jumat', 8, 9, 'Koding dan Kecerdasan Artifisial', 'Ruly Dwi Setyaningrum, S.Kom'],
                ['X AK 4', 'Jumat', 10, 13, 'Dasar AKL', 'Titin Sukmasari, S.Pd., M.Pd'],
                ['X ULW', 'Senin', 2, 4, 'IPAS', 'Ista Nofasari, S.Pd'],
                ['X ULW', 'Senin', 5, 8, 'Informatika', 'Siswanti Purwaningsih, S.T., M.Pd'],
                ['X ULW', 'Senin', 9, 13, 'Bahasa Jawa', 'Laili Ermawati, S.Pd'],
                ['X ULW', 'Selasa', 1, 3, 'Pendidikan Agama Islam dan Budi Pekerti', 'Mufatiroh, S.Ag'],
                ['X ULW', 'Selasa', 4, 6, 'PJOK', 'Bella Prakoso, S.Pd'],
                ['X ULW', 'Selasa', 7, 8, 'Dasar ULP', 'Risqi Nur Imama S.Tr.Par'],
                ['X ULW', 'Selasa', 9, 13, 'Bahasa Inggris', 'Fitria Renytasari, S.Pd'],
                ['X ULW', 'Rabu', 1, 2, 'Bahasa Indonesia', 'Sri Rahayu, S.Pd'],
                ['X ULW', 'Rabu', 3, 6, 'Dasar ULP', 'Risqi Nur Imama, S.Tr.Par'],
                ['X ULW', 'Rabu', 7, 8, 'Matematika', 'Dwi Nova Setyandari S.Pd'],
                ['X ULW', 'Rabu', 9, 13, 'Bahasa Inggris', 'Fitria Renytasari, S.Pd'],
                ['X ULW', 'Kamis', 1, 2, 'Bahasa Indonesia', 'Sri Rahayu, S.Pd'],
                ['X ULW', 'Kamis', 3, 6, 'Dasar ULP', 'Risqi Nur Imama, S.Tr.Par'],
                ['X ULW', 'Kamis', 7, 8, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['X ULW', 'Kamis', 9, 13, 'Sejarah', 'Fajar Luthfianto, S.Pd'],
                ['X ULW', 'Jumat', 2, 2, 'BK', 'Niken Hari Pratiwi, S.Psi.,M.Pd'],
                ['X ULW', 'Jumat', 3, 4, 'Dasar ULP', 'Risqi Nur Imama, S.Tr.Par'],
                ['X ULW', 'Jumat', 5, 6, 'Seni Budaya', 'Angga Widhy Wirawan, S.Pd.,M.Pd'],
                ['X ULW', 'Jumat', 7, 8, 'Koding dan Kecerdasan Artifisial', 'Shinta Indyar Shanty Susanto, S.Kom'],
                ['X ULW', 'Jumat', 9, 11, 'IPAS', 'Ista Nofasari, S.Pd'],
                ['X ULW', 'Jumat', 12, 13, 'Matematika', 'Dwi Nova Setyandari, S.Pd'],
                ['X DKV 1', 'Senin', 2, 4, 'Pendidikan Agama Islam dan Budi Pekerti', 'Dra. Hanik Pangestuti'],
                ['X DKV 1', 'Senin', 5, 7, 'IPAS', 'Khuriyatul Kamila, S.Si'],
                ['X DKV 1', 'Senin', 8, 13, 'Dasar DKV', 'Danang Anjar Hymawanto, S.Pd'],
                ['X DKV 1', 'Selasa', 1, 1, 'BK', 'Nur Eko Wahyuningsi h, S.Pd'],
                ['X DKV 1', 'Selasa', 2, 3, 'Bahasa Inggris', 'Fajar Wahyu Pratiwi, S.S'],
                ['X DKV 1', 'Selasa', 4, 6, 'Dasar DKV', 'Agus Pramono, S.Sn'],
                ['X DKV 1', 'Selasa', 7, 8, 'Bahasa Jawa', 'Khoyrotun Hisani, S.Sn'],
                ['X DKV 1', 'Selasa', 9, 13, 'Bahasa Indonesia', 'Erna Rinawati, S.Pd'],
                ['X DKV 1', 'Rabu', 1, 2, 'Matematika', 'Rulik Indrawati, S.Pd'],
                ['X DKV 1', 'Rabu', 3, 5, 'PJOK', 'Ilham Sungeidi, S.Pd'],
                ['X DKV 1', 'Rabu', 6, 8, 'Dasar DKV', 'Khoyrotun Hisani, S.Sn'],
                ['X DKV 1', 'Rabu', 9, 13, 'Koding dan Kecerdasan Artifisial', 'Endik Kuswantoro, S.Kom.,M.T'],
                ['X DKV 1', 'Kamis', 1, 2, 'Informatika', 'Elysa Yuli Nur\'aini, S.Si'],
                ['X DKV 1', 'Kamis', 3, 4, 'Bahasa Inggris', 'Fajar Wahyu Pratiwi, S.S'],
                ['X DKV 1', 'Kamis', 5, 6, 'Seni Budaya', 'Anang Prasetyo, S.Pd'],
                ['X DKV 1', 'Kamis', 7, 8, 'Sejarah', 'Yustin Febrini, S.Pd'],
                ['X DKV 1', 'Kamis', 9, 13, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['X DKV 1', 'Jumat', 2, 4, 'Dasar DKV', 'Agus Pramono, S.Sn'],
                ['X DKV 1', 'Jumat', 5, 6, 'Matematika', 'Rulik Indrawati, S.Pd'],
                ['X DKV 1', 'Jumat', 7, 9, 'IPAS', 'Khuriyatul Kamila, S.Si'],
                ['X DKV 1', 'Jumat', 10, 11, 'Informatika', 'Elysa Yuli Nur\'aini, S.Si'],
                ['X DKV 1', 'Jumat', 12, 13, 'Bahasa Indonesia', 'Erna Rinawati, S.Pd'],
                ['X DKV 2', 'Senin', 2, 3, 'Koding dan Kecerdasan Artifisial', 'Endik Kuswantoro, S.Kom.,M.T'],
                ['X DKV 2', 'Senin', 4, 5, 'Sejarah', 'Yustin Febrini, S.Pd'],
                ['X DKV 2', 'Senin', 6, 8, 'Dasar DKV', 'Agus Pramono, S.Sn'],
                ['X DKV 2', 'Senin', 9, 13, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['X DKV 2', 'Selasa', 1, 3, 'IPAS', 'Fitri Amaliyah, S.Pd'],
                ['X DKV 2', 'Selasa', 4, 5, 'Bahasa Indonesia', 'Erna Rinawati, S.Pd'],
                ['X DKV 2', 'Selasa', 6, 7, 'Bahasa Inggris', 'Fajar Wahyu Pratiwi, S.S'],
                ['X DKV 2', 'Selasa', 8, 13, 'Pendidikan Agama Islam dan Budi Pekerti', 'Dra. Hanik Pangestuti'],
                ['X DKV 2', 'Rabu', 1, 2, 'Informatika', 'Elysa Yuli Nur\'aini, S.Si'],
                ['X DKV 2', 'Rabu', 3, 3, 'BK', 'Yuni Jiastuti, S.Pd'],
                ['X DKV 2', 'Rabu', 4, 6, 'Dasar DKV', 'Agus Pramono, S.Sn'],
                ['X DKV 2', 'Rabu', 7, 8, 'Matematika', 'Ajeng Okvitasari, S.Pd'],
                ['X DKV 2', 'Rabu', 9, 13, 'Bahasa Indonesia', 'Erna Rinawati, S.Pd'],
                ['X DKV 2', 'Kamis', 1, 2, 'Bahasa Inggris', 'Fajar Wahyu Pratiwi, S.S'],
                ['X DKV 2', 'Kamis', 3, 5, 'PJOK', 'Ilham Sungeidi, S.Pd'],
                ['X DKV 2', 'Kamis', 6, 7, 'Informatika', 'Elysa Yuli Nur\'aini, S.Si'],
                ['X DKV 2', 'Kamis', 8, 13, 'Dasar DKV', 'Danang Anjar Hymawanto, S.Pd'],
                ['X DKV 2', 'Jumat', 2, 3, 'Seni Budaya', 'Anang Prasetyo, S.Pd'],
                ['X DKV 2', 'Jumat', 4, 5, 'Bahasa Jawa', 'Khoyrotun Hisani, S.Sn'],
                ['X DKV 2', 'Jumat', 6, 8, 'Dasar DKV', 'Khoyrotun Hisani, S.Sn'],
                ['X DKV 2', 'Jumat', 9, 10, 'Matematika', 'Ajeng Okvitasari, S.Pd'],
                ['X DKV 2', 'Jumat', 11, 13, 'IPAS', 'Fitri Amaliyah, S.Pd'],
                ['X PSPT 1', 'Senin', 2, 4, 'PJOK', 'Bella Prakoso, S.Pd'],
                ['X PSPT 1', 'Senin', 5, 6, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['X PSPT 1', 'Senin', 7, 13, 'Dasar BP', 'Benny Mamora, S.Kom'],
                ['X PSPT 1', 'Selasa', 1, 4, 'Dasar BP', 'Benny Mamora, S.Kom'],
                ['X PSPT 1', 'Selasa', 5, 6, 'Seni Budaya', 'Anang Prasetyo, S.Pd'],
                ['X PSPT 1', 'Selasa', 7, 8, 'Matematika', 'Eko Saputro, S.Pd'],
                ['X PSPT 1', 'Selasa', 9, 13, 'Bahasa Indonesia', 'Winartin, S.Pd'],
                ['X PSPT 1', 'Rabu', 1, 3, 'Pendidikan Agama Islam dan Budi Pekerti', 'Dra. Hanik Pangestuti'],
                ['X PSPT 1', 'Rabu', 4, 6, 'IPAS', 'Ista Nofasari, S.Pd'],
                ['X PSPT 1', 'Rabu', 7, 8, 'Bahasa Inggris', 'Muto\'atul Khosi\'ah, S.Pd'],
                ['X PSPT 1', 'Rabu', 9, 13, 'Bahasa Indonesia', 'Winartin, S.Pd'],
                ['X PSPT 1', 'Kamis', 1, 2, 'Koding dan Kecerdasan Artifisial', 'Elyana Frisca Monica, S.Pd'],
                ['X PSPT 1', 'Kamis', 3, 6, 'Informatika', 'Elyana Frisca Monica, S.Pd'],
                ['X PSPT 1', 'Kamis', 7, 8, 'Bahasa Jawa', 'Khoyrotun Hisani, S.Sn'],
                ['X PSPT 1', 'Kamis', 9, 13, 'Matematika', 'Eko Saputro, S.Pd'],
                ['X PSPT 1', 'Jumat', 2, 3, 'Sejarah', 'Yustin Febrini, S.Pd'],
                ['X PSPT 1', 'Jumat', 4, 5, 'Bahasa Inggris', 'Muto\'atul Khosi\'ah, S.Pd'],
                ['X PSPT 1', 'Jumat', 6, 8, 'IPAS', 'Ista Nofasari, S.Pd'],
                ['X PSPT 1', 'Jumat', 9, 9, 'BK', 'Winarsih, S.Pd, M.Pd'],
                ['X PSPT 1', 'Jumat', 10, 13, 'Dasar BP', 'Benny Mamora, S.Kom'],
                ['X PSPT 2', 'Senin', 2, 5, 'Informatika', 'Elyana Frisca Monica, S.Pd'],
                ['X PSPT 2', 'Senin', 6, 7, 'Bahasa Inggris', 'Muto\'atul Khosi\'ah, S.Pd'],
                ['X PSPT 2', 'Senin', 8, 13, 'IPAS', 'Ista Nofasari, S.Pd'],
                ['X PSPT 2', 'Selasa', 1, 3, 'IPAS', 'Ista Nofasari, S.Pd'],
                ['X PSPT 2', 'Selasa', 4, 5, 'Sejarah', 'Yustin Febrini, S.Pd'],
                ['X PSPT 2', 'Selasa', 6, 6, 'BK', 'Winarsih, S.Pd, M.Pd'],
                ['X PSPT 2', 'Selasa', 7, 13, 'Dasar BP', 'Sa\'ad Wazis Hiedayat, S.Pd'],
                ['X PSPT 2', 'Rabu', 1, 4, 'Dasar BP', 'Sa\'ad Wazis Hiedayat, S.Pd'],
                ['X PSPT 2', 'Rabu', 5, 7, 'PJOK', 'Bella Prakoso, S.Pd'],
                ['X PSPT 2', 'Rabu', 8, 13, 'Pendidikan Agama Islam dan Budi Pekerti', 'Dra. Hanik Pangestuti'],
                ['X PSPT 2', 'Kamis', 1, 2, 'Bahasa Indonesia', 'Umi Kulsum, S.Pd'],
                ['X PSPT 2', 'Kamis', 3, 4, 'Matematika', 'Laili Ermawati, S.Pd'],
                ['X PSPT 2', 'Kamis', 5, 6, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['X PSPT 2', 'Kamis', 7, 8, 'Bahasa Jawa', 'Muhammad Fajar Assidiqi, S.Pd'],
                ['X PSPT 2', 'Kamis', 9, 13, 'Bahasa Inggris', 'Muto\'atul Khosi\'ah, S.Pd'],
                ['X PSPT 2', 'Jumat', 2, 3, 'Koding dan Kecerdasan Artifisial', 'Elyana Frisca Monica S.Pd'],
                ['X PSPT 2', 'Jumat', 4, 7, 'Dasar BP', 'Sa\'ad Wazis Hiedayat, S.Pd'],
                ['X PSPT 2', 'Jumat', 8, 9, 'Seni Budaya', 'Anang Prasetyo, S.Pd'],
                ['X PSPT 2', 'Jumat', 10, 11, 'Matematika', 'Laili Ermawati, S.Pd'],
                ['X PSPT 2', 'Jumat', 12, 13, 'Bahasa Indonesia', 'Umi Kulsum, S.Pd'],
                ['X AN 1', 'Senin', 2, 3, 'Sejarah', 'Yustin Febrini, S.Pd'],
                ['X AN 1', 'Senin', 4, 5, 'Seni Budaya', 'Anang Prasetyo, S.Pd'],
                ['X AN 1', 'Senin', 6, 6, 'BK', 'Siti Maisaroh, S.Pd'],
                ['X AN 1', 'Senin', 7, 8, 'Bahasa Indonesia', 'Siti Khoiriyah, S.Pd'],
                ['X AN 1', 'Senin', 9, 13, 'Bahasa Inggris', 'Agus Muharyanto, M.Pd'],
                ['X AN 1', 'Selasa', 1, 3, 'Pendidikan Agama Islam dan Budi Pekerti', 'Muashofah, M.Pd'],
                ['X AN 1', 'Selasa', 4, 5, 'Bahasa Indonesia', 'Siti Khoiriyah, S.Pd'],
                ['X AN 1', 'Selasa', 6, 7, 'Informatika', 'Tuhu Eries Kudori, S.Sn'],
                ['X AN 1', 'Selasa', 8, 13, 'Dasar AN', 'Rika Okta Maulida, S.Ds.'],
                ['X AN 1', 'Rabu', 1, 3, 'Dasar AN', 'Dhuana Putri Puspitasary, S.Pd'],
                ['X AN 1', 'Rabu', 4, 5, 'Pendidikan Pancasila', 'Mega Mahardika, S.Pd'],
                ['X AN 1', 'Rabu', 6, 7, 'Matematika', 'Arvia Rienetasary, S.Pd'],
                ['X AN 1', 'Rabu', 8, 13, 'IPAS', 'Indriati, S.Pd'],
                ['X AN 1', 'Kamis', 1, 2, 'Bahasa Inggris', 'Agus Muharyanto, M.Pd'],
                ['X AN 1', 'Kamis', 3, 4, 'Matematika', 'Arvia Rienetasary, S.Pd'],
                ['X AN 1', 'Kamis', 5, 7, 'PJOK', 'Bella Prakoso, S.Pd'],
                ['X AN 1', 'Kamis', 8, 13, 'Dasar AN', 'Dhuana Putri Puspitasary, S.Pd'],
                ['X AN 1', 'Jumat', 2, 4, 'IPAS', 'Indriati, S.Pd'],
                ['X AN 1', 'Jumat', 5, 6, 'Bahasa Jawa', 'Muhammad Fajar Assidiqi S.Pd'],
                ['X AN 1', 'Jumat', 7, 9, 'Dasar AN', 'Rika Okta Maulida, S.Ds.'],
                ['X AN 1', 'Jumat', 10, 11, 'Koding dan Kecerdasan Artifisial', 'Endik Kuswantoro, S.Kom.,M.T'],
                ['X AN 1', 'Jumat', 12, 13, 'Informatika', 'Tuhu Eries Kudori, S.Sn'],
                ['X AN 2', 'Senin', 2, 4, 'Pendidikan Agama Islam dan Budi Pekerti', 'Muashofah, M.Pd'],
                ['X AN 2', 'Senin', 5, 6, 'Koding dan Kecerdasan Artifisial', 'Endik Kuswantoro, S.Kom.,M.T'],
                ['X AN 2', 'Senin', 7, 8, 'Sejarah', 'Yustin Febrini, S.Pd'],
                ['X AN 2', 'Senin', 9, 13, 'Matematika', 'Ajeng Okvitasari, S.Pd'],
                ['X AN 2', 'Selasa', 1, 3, 'PJOK', 'Bella Prakoso, S.Pd'],
                ['X AN 2', 'Selasa', 4, 5, 'Matematika', 'Ajeng Okvitasari, S.Pd'],
                ['X AN 2', 'Selasa', 6, 7, 'Pendidikan Pancasila', 'Mega Mahardika, S.Pd'],
                ['X AN 2', 'Selasa', 8, 9, 'Bahasa Inggris', 'Agus Muharyanto, M.Pd'],
                ['X AN 2', 'Selasa', 10, 13, 'BK', 'Siti Maisaroh, S.Pd'],
                ['X AN 2', 'Rabu', 1, 3, 'IPAS', 'Indriati, S.Pd'],
                ['X AN 2', 'Rabu', 4, 5, 'Bahasa Indonesia', 'Siti Khoiriyah, S.Pd'],
                ['X AN 2', 'Rabu', 6, 7, 'Seni Budaya', 'Anang Prasetyo, S.Pd'],
                ['X AN 2', 'Rabu', 8, 13, 'Dasar AN', 'Rika Okta Maulida, S.Ds.'],
                ['X AN 2', 'Kamis', 1, 2, 'Bahasa Indonesia', 'Siti Khoiriyah, S.Pd'],
                ['X AN 2', 'Kamis', 3, 4, 'Bahasa Inggris', 'Agus Muharyanto, M.Pd'],
                ['X AN 2', 'Kamis', 5, 7, 'Dasar AN', 'Dhuana Putri Puspitasary, S.Pd'],
                ['X AN 2', 'Kamis', 8, 13, 'Dasar AN', 'Rika Okta Maulida, S.Ds.'],
                ['X AN 2', 'Jumat', 2, 3, 'Bahasa Jawa', 'Muhammad Fajar Assidiqi S.Pd'],
                ['X AN 2', 'Jumat', 4, 5, 'Informatika', 'Rika Okta Maulida, S.Ds.'],
                ['X AN 2', 'Jumat', 6, 8, 'IPAS', 'Indriati, S.Pd'],
                ['X AN 2', 'Jumat', 9, 11, 'Dasar AN', 'Dhuana Putri Puspitasary, S.Pd'],
                ['X AN 2', 'Jumat', 12, 13, 'Informatika', 'Rika Okta Maulida, S.Ds.'],
                ['XI TKI 1', 'Senin', 2, 3, 'Konsentrasi TKI', 'Baskoro, S.Si'],
                ['XI TKI 1', 'Senin', 4, 6, 'Konsentrasi TKI', 'Ayu Puspitorini, ST'],
                ['XI TKI 1', 'Senin', 7, 13, 'Konsentrasi TKI', 'Diana Hartanti, S.T., M.Pd'],
                ['XI TKI 1', 'Selasa', 1, 2, 'Bahasa Jepang', 'Rizki Putri Wulandari, S.Pd'],
                ['XI TKI 1', 'Selasa', 3, 4, 'Bahasa Inggris', 'Agus Muharyanto, M.Pd'],
                ['XI TKI 1', 'Selasa', 8, 13, 'Matematika', 'Basuki Sarjono, S.Pd'],
                ['XI TKI 1', 'Rabu', 1, 2, 'Bahasa Jawa', 'Yustin Febrini, S.Pd'],
                ['XI TKI 1', 'Rabu', 3, 4, 'Konsentrasi TKI', 'Rifkotin Na\'imah, S.Pd'],
                ['XI TKI 1', 'Rabu', 7, 8, 'Mapel Pilihan TKI', 'Sri Kusumastuti, S.Pd'],
                ['XI TKI 1', 'Rabu', 9, 13, 'Pendidikan Pancasila', 'Sri Kusumastuti, S.Pd'],
                ['XI TKI 1', 'Kamis', 1, 3, 'Bahasa Indonesia', 'Yani, S.Pd.'],
                ['XI TKI 1', 'Kamis', 4, 5, 'Sejarah', 'Baskoro, S.Si'],
                ['XI TKI 1', 'Kamis', 6, 7, 'PJOK', 'Ilham Sungeidi, S.Pd'],
                ['XI TKI 1', 'Kamis', 8, 13, 'Pendidikan Agama Islam dan Budi Pekerti', 'Mufatiroh, S.Ag'],
                ['XI TKI 1', 'Jumat', 2, 4, 'Konsentrasi TKI', 'Ayu Puspitorini, ST'],
                ['XI TKI 1', 'Jumat', 5, 8, 'Konsentrasi TKI', 'Diana Hartanti, S.T., M.Pd'],
                ['XI TKI 1', 'Jumat', 9, 10, 'Bahasa Inggris', 'Agus Muharyanto, M.Pd'],
                ['XI TKI 1', 'Jumat', 11, 13, 'BK', 'Yuni Jiastuti, S.Pd'],
                ['XI TKI 2', 'Senin', 2, 3, 'PJOK', 'Ilham Sungeidi, S.Pd'],
                ['XI TKI 2', 'Senin', 4, 6, 'Matematika', 'Basuki Sarjono, S.Pd'],
                ['XI TKI 2', 'Senin', 7, 8, 'Bahasa Jepang', 'Rizki Putri Wulandari, S.Pd'],
                ['XI TKI 2', 'Senin', 9, 13, 'Bahasa Inggris', 'Komariyah, S.Pd'],
                ['XI TKI 2', 'Selasa', 3, 4, 'Konsentrasi TKI', 'Baskoro, S.Si'],
                ['XI TKI 2', 'Selasa', 5, 6, 'Konsentrasi TKI', 'Rifkotin Na\'imah, S.Pd'],
                ['XI TKI 2', 'Selasa', 7, 8, 'Mapel Pilihan TKI', 'Sri Kusumastuti, S.Pd'],
                ['XI TKI 2', 'Selasa', 9, 13, 'Pendidikan Pancasila', 'Sri Kusumastuti, S.Pd'],
                ['XI TKI 2', 'Rabu', 1, 3, 'Bahasa Indonesia', 'Yani, S.Pd.'],
                ['XI TKI 2', 'Rabu', 4, 6, 'Konsentrasi TKI', 'Ayu Puspitorini, ST'],
                ['XI TKI 2', 'Rabu', 7, 13, 'Konsentrasi TKI', 'Diana Hartanti, S.T., M.Pd'],
                ['XI TKI 2', 'Kamis', 1, 3, 'Pendidikan Agama Islam dan Budi Pekerti', 'Mufatiroh, S.Ag'],
                ['XI TKI 2', 'Kamis', 4, 7, 'Konsentrasi TKI', 'Diana Hartanti, S.T., M.Pd'],
                ['XI TKI 2', 'Kamis', 8, 13, 'Konsentrasi TKI', 'Ayu Puspitorini, ST'],
                ['XI TKI 2', 'Jumat', 2, 3, 'Sejarah', 'Baskoro, S.Si'],
                ['XI TKI 2', 'Jumat', 7, 8, 'Bahasa Inggris', 'Komariyah, S.Pd'],
                ['XI TKI 2', 'Jumat', 9, 10, 'BK', 'Yuni Jiastuti, S.Pd'],
                ['XI TKI 2', 'Jumat', 11, 13, 'Bahasa Jawa', 'Yustin Febrini, S.Pd'],
                ['XI RPL 1', 'Senin', 2, 4, 'Pendidikan Agama Islam dan Budi Pekerti', 'Mufatiroh, S.Ag'],
                ['XI RPL 1', 'Senin', 5, 6, 'BK', 'Widodo, S.Pd'],
                ['XI RPL 1', 'Senin', 7, 13, 'Konsentrasi RPL', 'Kurnila Putri Islamawati, S.Pd'],
                ['XI RPL 1', 'Selasa', 1, 4, 'Konsentrasi RPL', 'Kurnila Putri Islamawati, S.Pd'],
                ['XI RPL 1', 'Selasa', 5, 7, 'Konsentrasi RPL', 'Shinta Indyar Shanty Susanto, S.Kom'],
                ['XI RPL 1', 'Rabu', 1, 4, 'Konsentrasi RPL', 'Shinta Indyar Shanty Susanto, S.Kom'],
                ['XI RPL 1', 'Rabu', 5, 6, 'Bahasa Inggris', 'Isti Mufadah, S.Pd'],
                ['XI RPL 1', 'Rabu', 7, 8, 'Sejarah', 'Erna Qoriah, S.E.'],
                ['XI RPL 1', 'Rabu', 9, 13, 'Bahasa Jawa', 'Laili Ermawati, S.Pd'],
                ['XI RPL 1', 'Kamis', 1, 3, 'Konsentrasi RPL', 'Shinta Indyar Shanty Susanto, S.Kom'],
                ['XI RPL 1', 'Kamis', 4, 5, 'Mapel Pilihan RPL', 'Hendro Suwignyo, ST'],
                ['XI RPL 1', 'Kamis', 6, 7, 'PJOK', 'Zainul Arifin,S.Pd'],
                ['XI RPL 1', 'Kamis', 8, 13, 'Bahasa Indonesia', 'Umi Kulsum, S.Pd'],
                ['XI RPL 1', 'Jumat', 4, 5, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['XI RPL 1', 'Jumat', 6, 7, 'Bahasa Jepang', 'Sulistyowati, SS'],
                ['XI RPL 1', 'Jumat', 8, 9, 'Bahasa Inggris', 'Isti Mufadah, S.Pd'],
                ['XI RPL 1', 'Jumat', 10, 13, 'Matematika', 'Lutfia Marsalina, S.Pd.I, M.Pd.'],
                ['XI RPL 2', 'Senin', 5, 6, 'Bahasa Inggris', 'Fajar Wahyu Pratiwi, S.S'],
                ['XI RPL 2', 'Senin', 7, 13, 'Konsentrasi RPL', 'Badrus Sulaiman, S.Pd.'],
                ['XI RPL 2', 'Selasa', 1, 3, 'Matematika', 'Lutfia Marsalina, S.Pd.I, M.Pd.'],
                ['XI RPL 2', 'Selasa', 4, 5, 'Bahasa Inggris', 'Fajar Wahyu Pratiwi, S.S'],
                ['XI RPL 2', 'Selasa', 6, 7, 'PJOK', 'Zainul Arifin,S.Pd'],
                ['XI RPL 2', 'Selasa', 8, 13, 'Konsentrasi RPL', 'Badrus Sulaiman, S.Pd.'],
                ['XI RPL 2', 'Rabu', 1, 4, 'Konsentrasi RPL', 'Kurnila Putri Islamawati, S.Pd'],
                ['XI RPL 2', 'Rabu', 5, 6, 'Mapel Pilihan RPL', 'Hendro Suwignyo, ST'],
                ['XI RPL 2', 'Rabu', 7, 8, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['XI RPL 2', 'Rabu', 9, 13, 'Sejarah', 'Erna Qoriah, S.E.'],
                ['XI RPL 2', 'Kamis', 1, 2, 'Bahasa Jepang', 'Sulistyowati, SS'],
                ['XI RPL 2', 'Kamis', 3, 4, 'BK', 'Widodo, S.Pd'],
                ['XI RPL 2', 'Kamis', 5, 6, 'Bahasa Jawa', 'Laili Ermawati, S.Pd'],
                ['XI RPL 2', 'Kamis', 7, 13, 'Konsentrasi RPL', 'Kurnila Putri Islamawati, S.Pd'],
                ['XI RPL 2', 'Jumat', 2, 4, 'Bahasa Indonesia', 'Winartin, S.Pd'],
                ['XI RPL 2', 'Jumat', 5, 7, 'Pendidikan Agama Islam dan Budi Pekerti', 'Mufatiroh, S.Ag'],
                ['XI RPL 2', 'Jumat', 8, 10, 'Konsentrasi RPL', 'Badrus Sulaiman, S.Pd.'],
                ['XI TKJ 1', 'Senin', 2, 3, 'Bahasa Jepang', 'Sulistyowati, SS'],
                ['XI TKJ 1', 'Senin', 4, 6, 'Bahasa Indonesia', 'Sri Rahayu, S.Pd'],
                ['XI TKJ 1', 'Senin', 7, 13, 'Konsentrasi TKJ', 'Siti Munawaroh, S.Kom.,M.Pd'],
                ['XI TKJ 1', 'Selasa', 1, 2, 'Bahasa Inggris', 'Isti Mufadah, S.Pd'],
                ['XI TKJ 1', 'Selasa', 6, 7, 'PJOK', 'Ilham Sungeidi, S.Pd'],
                ['XI TKJ 1', 'Selasa', 8, 13, 'Konsentrasi TKJ', 'Siswanti Purwaningsih, S.T., M.Pd'],
                ['XI TKJ 1', 'Rabu', 1, 2, 'Sejarah', 'Baskoro, S.Si'],
                ['XI TKJ 1', 'Rabu', 3, 4, 'Bahasa Inggris', 'Isti Mufadah, S.Pd'],
                ['XI TKJ 1', 'Rabu', 5, 6, 'Mapel Pilihan TKJ', 'Listyana Hartati, S.Kom., M.Pd'],
                ['XI TKJ 1', 'Rabu', 7, 8, 'Konsentrasi TKJ', 'Endang Ary Handayani, S.T., M.Pd'],
                ['XI TKJ 1', 'Rabu', 9, 13, 'Bahasa Jawa', 'Luluk Munfarida,S.Pd'],
                ['XI TKJ 1', 'Kamis', 1, 3, 'Pendidikan Agama Islam dan Budi Pekerti', 'Dra. Hanik Pangestuti'],
                ['XI TKJ 1', 'Kamis', 4, 5, 'BK', 'Nishfu Laili,S.Pd'],
                ['XI TKJ 1', 'Kamis', 6, 13, 'Konsentrasi TKJ', 'Listyana Hartati, S.Kom.,M.Pd'],
                ['XI TKJ 1', 'Jumat', 2, 4, 'Matematika', 'Lutfia Marsalina, S.Pd.I, M.Pd.'],
                ['XI TKJ 1', 'Jumat', 5, 8, 'Konsentrasi TKJ', 'Ary Sunaryo, ST.,M.Pd'],
                ['XI TKJ 1', 'Jumat', 9, 10, 'Pendidikan Pancasila', 'Fitri Amaliyah, S.Pd'],
                ['XI TKJ 2', 'Senin', 2, 3, 'Bahasa Jawa', 'Luluk Munfarida,S.Pd'],
                ['XI TKJ 2', 'Senin', 4, 5, 'Konsentrasi TKJ', 'Endang Ary Handayani, S.T., M.Pd'],
                ['XI TKJ 2', 'Senin', 6, 8, 'Pendidikan Agama Islam dan Budi Pekerti', 'Dra. Hanik Pangestuti'],
                ['XI TKJ 2', 'Senin', 9, 13, 'Bahasa Inggris', 'Isti Mufadah, S.Pd'],
                ['XI TKJ 2', 'Selasa', 1, 3, 'Matematika', 'Elysa Yuli Nur\'aini, S.Si'],
                ['XI TKJ 2', 'Selasa', 6, 13, 'Konsentrasi TKJ', 'Listyana Hartati, S.Kom.,M.Pd'],
                ['XI TKJ 2', 'Rabu', 1, 2, 'PJOK', 'Ilham Sungeidi, S.Pd'],
                ['XI TKJ 2', 'Rabu', 3, 4, 'Mapel Pilihan TKJ', 'Listyana Hartati, S.Kom., M.Pd'],
                ['XI TKJ 2', 'Rabu', 5, 6, 'BK', 'Nishfu Laili,S.Pd'],
                ['XI TKJ 2', 'Rabu', 7, 13, 'Konsentrasi TKJ', 'Ary Sunaryo, ST.,M.Pd'],
                ['XI TKJ 2', 'Kamis', 1, 2, 'Sejarah', 'Baskoro, S.Si'],
                ['XI TKJ 2', 'Kamis', 3, 4, 'Bahasa Inggris', 'Isti Mufadah, S.Pd'],
                ['XI TKJ 2', 'Kamis', 5, 7, 'Konsentrasi TKJ', 'Siswanti Purwaningsih, S.T., M.Pd'],
                ['XI TKJ 2', 'Jumat', 2, 3, 'Pendidikan Pancasila', 'Fitri Amaliyah, S.Pd'],
                ['XI TKJ 2', 'Jumat', 4, 6, 'Bahasa Indonesia', 'Sri Rahayu, S.Pd'],
                ['XI TKJ 2', 'Jumat', 7, 10, 'Konsentrasi TKJ', 'Siti Munawaroh, S.Kom.,M.Pd'],
                ['XI TKJ 2', 'Jumat', 11, 13, 'Bahasa Jepang', 'Sulistyowati, SS'],
                ['XI BD 1', 'Senin', 2, 3, 'Bahasa Jawa', 'Muhammad Fajar Assidiqi, S.Pd'],
                ['XI BD 1', 'Senin', 7, 13, 'Mapel Pilihan BD', 'Andri Krisdianto, SE.,M.Pd'],
                ['XI BD 1', 'Selasa', 1, 2, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['XI BD 1', 'Selasa', 3, 4, 'Bahasa Inggris', 'Dwi Rini Manfaati, S.Pd'],
                ['XI BD 1', 'Selasa', 5, 7, 'Konsentrasi BD', 'Nurul Azizah, S.Pd'],
                ['XI BD 1', 'Selasa', 8, 13, 'Pendidikan Agama Islam dan Budi Pekerti', 'Sinta Lestari, S.Pd.I'],
                ['XI BD 1', 'Rabu', 3, 5, 'Matematika', 'Arvia Rienetasary, S.Pd'],
                ['XI BD 1', 'Rabu', 6, 7, 'PJOK', 'Agus Fahruddy, S.Pd., M.Pd'],
                ['XI BD 1', 'Rabu', 8, 13, 'Konsentrasi BD', 'Niken Dewi Hastika, S.Pd'],
                ['XI BD 1', 'Kamis', 1, 2, 'BK', 'Nur Eko Wahyuningsih, S.Pd'],
                ['XI BD 1', 'Kamis', 3, 4, 'Konsentrasi BD', 'Andri Krisdianto, SE., M.Pd'],
                ['XI BD 1', 'Kamis', 5, 8, 'Konsentrasi BD', 'Agung Yulianto, S.Pd'],
                ['XI BD 1', 'Kamis', 9, 13, 'Konsentrasi BD', 'Niken Dewi Hastika, S.Pd'],
                ['XI BD 1', 'Jumat', 2, 3, 'Konsentrasi BD', 'Nurul Azizah, S.Pd'],
                ['XI BD 1', 'Jumat', 4, 5, 'Konsentrasi BD', 'Luluk Munfarida,S.Pd'],
                ['XI BD 1', 'Jumat', 6, 7, 'Sejarah', 'Dra. Anik Indriani'],
                ['XI BD 1', 'Jumat', 8, 10, 'Bahasa Indonesia', 'Erna Rinawati, S.Pd'],
                ['XI BD 1', 'Jumat', 11, 13, 'Bahasa Inggris', 'Dwi Rini Manfaati, S.Pd'],
                ['XI BD 2', 'Senin', 2, 5, 'Konsentrasi BD', 'Agung Yulianto, S.Pd'],
                ['XI BD 2', 'Senin', 6, 7, 'Sejarah', 'Dra. Anik Indriani'],
                ['XI BD 2', 'Senin', 8, 13, 'Bahasa Indonesia', 'Erna Rinawati, S.Pd'],
                ['XI BD 2', 'Selasa', 1, 3, 'Matematika', 'Arvia Rienetasary, S.Pd'],
                ['XI BD 2', 'Selasa', 4, 7, 'Mapel Pilihan BD', 'Andri Krisdianto, SE.,M.Pd'],
                ['XI BD 2', 'Selasa', 8, 13, 'Konsentrasi BD', 'Nurul Azizah, S.Pd'],
                ['XI BD 2', 'Rabu', 1, 2, 'PJOK', 'Agus Fahruddy, S.Pd., M.Pd'],
                ['XI BD 2', 'Rabu', 3, 4, 'Konsentrasi BD', 'Niken Dewi Hastika, S.Pd'],
                ['XI BD 2', 'Rabu', 7, 8, 'Konsentrasi BD', 'Andri Krisdianto, SE., M.Pd'],
                ['XI BD 2', 'Rabu', 9, 13, 'Bahasa Inggris', 'Dwi Rini Manfaati, S.Pd'],
                ['XI BD 2', 'Kamis', 4, 6, 'Konsentrasi BD', 'Niken Dewi Hastika, S.Pd'],
                ['XI BD 2', 'Kamis', 7, 8, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['XI BD 2', 'Kamis', 9, 13, 'Bahasa Jawa', 'Muhammad Fajar Assidiqi, S.Pd'],
                ['XI BD 2', 'Jumat', 2, 3, 'Konsentrasi BD', 'Luluk Munfarida,S.Pd'],
                ['XI BD 2', 'Jumat', 4, 6, 'Pendidikan Agama Islam dan Budi Pekerti', 'Sinta Lestari, S.Pd.I'],
                ['XI BD 2', 'Jumat', 7, 8, 'Bahasa Inggris', 'Dwi Rini Manfaati, S.Pd'],
                ['XI BD 2', 'Jumat', 9, 10, 'BK', 'Dian Mawarti, S.Pd'],
                ['XI BD 2', 'Jumat', 11, 13, 'Konsentrasi BD', 'Luluk Munfarida,S.Pd'],
                ['XI BD 3', 'Senin', 2, 3, 'Sejarah', 'Dra. Anik Indriani'],
                ['XI BD 3', 'Senin', 4, 7, 'Mapel Pilihan BD', 'Niken Dewi Hastika, S.Pd'],
                ['XI BD 3', 'Selasa', 1, 2, 'BK', 'Dian Mawarti, S.Pd'],
                ['XI BD 3', 'Selasa', 3, 4, 'Konsentrasi BD', 'Luluk Munfarida,S.Pd'],
                ['XI BD 3', 'Selasa', 5, 8, 'Konsentrasi BD', 'Agung Yulianto, S.Pd'],
                ['XI BD 3', 'Selasa', 9, 13, 'Bahasa Jawa', 'Luluk Munfarida,S.Pd'],
                ['XI BD 3', 'Rabu', 1, 2, 'Konsentrasi BD', 'Niken Dewi Hastika, S.Pd'],
                ['XI BD 3', 'Rabu', 5, 7, 'Konsentrasi BD', 'Nurul Azizah, S.Pd'],
                ['XI BD 3', 'Rabu', 8, 13, 'Bahasa Indonesia', 'Umi Kulsum, S.Pd'],
                ['XI BD 3', 'Kamis', 1, 2, 'Bahasa Inggris', 'Dwi Rini Manfaati, S.Pd'],
                ['XI BD 3', 'Kamis', 3, 4, 'PJOK', 'Bella Prakoso, S.Pd'],
                ['XI BD 3', 'Kamis', 5, 7, 'Matematika', 'Ajeng Okvitasari, S.Pd'],
                ['XI BD 3', 'Kamis', 8, 13, 'Konsentrasi BD', 'Nurul Azizah, S.Pd'],
                ['XI BD 3', 'Jumat', 2, 4, 'Pendidikan Agama Islam dan Budi Pekerti', 'Fitria Diah Ayu Hartati, S.Pd'],
                ['XI BD 3', 'Jumat', 5, 6, 'Bahasa Inggris', 'Dwi Rini Manfaati, S.Pd'],
                ['XI BD 3', 'Jumat', 7, 8, 'Konsentrasi BD', 'Anisa Kusumawati, S.Pd'],
                ['XI BD 3', 'Jumat', 9, 10, 'Konsentrasi BD', 'Luluk Munfarida,S.Pd'],
                ['XI BD 3', 'Jumat', 11, 13, 'Pendidikan Pancasila', 'Nurul Azizah, S.Pd'],
                ['XI MP 1', 'Senin', 2, 5, 'Konsentrasi MP', 'Martiin, S.Pd'],
                ['XI MP 1', 'Senin', 6, 8, 'Bahasa Indonesia', 'Purwati,S.Pd'],
                ['XI MP 1', 'Senin', 9, 13, 'Mapel Pilihan MP', 'Tutut Sriatin, S.Pd'],
                ['XI MP 1', 'Selasa', 1, 2, 'Konsentrasi MP', 'Martiin, S.Pd'],
                ['XI MP 1', 'Selasa', 3, 5, 'Konsentrasi MP', 'Martiin, S.Pd'],
                ['XI MP 1', 'Selasa', 6, 8, 'Pendidikan Agama Islam dan Budi Pekerti', 'Fitria Diah Ayu Hartati, S.Pd'],
                ['XI MP 1', 'Selasa', 9, 13, 'Bahasa Inggris', 'Komariyah, S.Pd'],
                ['XI MP 1', 'Rabu', 3, 6, 'Konsentrasi MP', 'Martiin, S.Pd'],
                ['XI MP 1', 'Rabu', 7, 8, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['XI MP 1', 'Rabu', 9, 13, 'Bahasa Jepang', 'Sulistyowati, SS'],
                ['XI MP 1', 'Kamis', 1, 2, 'PJOK', 'Zainul Arifin,S.Pd'],
                ['XI MP 1', 'Kamis', 3, 4, 'Sejarah', 'Dra. Anik Indriani'],
                ['XI MP 1', 'Kamis', 8, 13, 'Matematika', 'Laili Ermawati, S.Pd'],
                ['XI MP 1', 'Jumat', 2, 3, 'Konsentrasi MP', 'Martiin, S.Pd'],
                ['XI MP 1', 'Jumat', 4, 6, 'Konsentrasi MP', 'Martiin, S.Pd'],
                ['XI MP 1', 'Jumat', 7, 8, 'BK', 'Veronica Damay Rulitasari, S.Pd'],
                ['XI MP 1', 'Jumat', 9, 10, 'Bahasa Inggris', 'Komariyah, S.Pd'],
                ['XI MP 1', 'Jumat', 11, 13, 'Bahasa Jawa', 'Muhammad Fajar Assidiqi, S.Pd'],
                ['XI MP 2', 'Senin', 4, 6, 'Matematika', 'Laili Ermawati, S.Pd'],
                ['XI MP 2', 'Senin', 7, 13, 'Konsentrasi MP', 'Sunarti, S.Pd'],
                ['XI MP 2', 'Selasa', 1, 3, 'Pendidikan Agama Islam dan Budi Pekerti', 'Fitria Diah Ayu Hartati, S.Pd'],
                ['XI MP 2', 'Selasa', 4, 5, 'PJOK', 'Zainul Arifin,S.Pd'],
                ['XI MP 2', 'Selasa', 6, 8, 'Konsentrasi MP', 'Sunarti, S.Pd'],
                ['XI MP 2', 'Selasa', 9, 13, 'Mapel Pilihan MP', 'Tutut Sriatin, S.Pd'],
                ['XI MP 2', 'Rabu', 1, 2, 'Konsentrasi MP', 'Sunarti, S.Pd'],
                ['XI MP 2', 'Rabu', 3, 4, 'Bahasa Jepang', 'Sulistyowati, SS'],
                ['XI MP 2', 'Rabu', 5, 6, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['XI MP 2', 'Rabu', 7, 8, 'Konsentrasi MP', 'Sunarti, S.Pd'],
                ['XI MP 2', 'Rabu', 9, 13, 'Bahasa Inggris', 'Komariyah, S.Pd'],
                ['XI MP 2', 'Kamis', 4, 5, 'Bahasa Jawa', 'Muhammad Fajar Assidiqi, S.Pd'],
                ['XI MP 2', 'Kamis', 6, 7, 'Sejarah', 'Dra. Anik Indriani'],
                ['XI MP 2', 'Kamis', 8, 13, 'Konsentrasi MP', 'Sunarti, S.Pd'],
                ['XI MP 2', 'Jumat', 2, 4, 'Bahasa Indonesia', 'Purwati,S.Pd'],
                ['XI MP 2', 'Jumat', 5, 6, 'Bahasa Inggris', 'Komariyah, S.Pd'],
                ['XI MP 2', 'Jumat', 7, 10, 'Konsentrasi MP', 'Sunarti, S.Pd'],
                ['XI MP 2', 'Jumat', 11, 13, 'BK', 'Siti Maisaroh, S.Pd'],
                ['XI MP 3', 'Senin', 2, 4, 'Matematika', 'Rulik Indrawati, S.Pd'],
                ['XI MP 3', 'Senin', 5, 6, 'Bahasa Jepang', 'Sulistyowati, SS'],
                ['XI MP 3', 'Senin', 7, 13, 'Konsentrasi MP', 'Titik Samsistini, S.Pd'],
                ['XI MP 3', 'Selasa', 4, 6, 'Bahasa Indonesia', 'Endang Safitri, S.Pd'],
                ['XI MP 3', 'Selasa', 7, 8, 'Konsentrasi MP', 'Titik Samsistini, S.Pd'],
                ['XI MP 3', 'Selasa', 9, 13, 'Konsentrasi MP', 'Titik Samsistini, S.Pd'],
                ['XI MP 3', 'Rabu', 1, 2, 'PJOK', 'Zainul Arifin,S.Pd'],
                ['XI MP 3', 'Rabu', 3, 6, 'Konsentrasi MP', 'Titik Samsistini, S.Pd'],
                ['XI MP 3', 'Rabu', 7, 8, 'Bahasa Inggris', 'Andri Retno Yuli Astuti, S.Pd'],
                ['XI MP 3', 'Rabu', 9, 13, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['XI MP 3', 'Kamis', 1, 3, 'Pendidikan Agama Islam dan Budi Pekerti', 'Fitria Diah Ayu Hartati, S.Pd'],
                ['XI MP 3', 'Kamis', 4, 6, 'Konsentrasi MP', 'Titik Samsistini, S.Pd'],
                ['XI MP 3', 'Kamis', 7, 8, 'BK', 'Veronica Damay Rulitasari, S.Pd'],
                ['XI MP 3', 'Kamis', 9, 13, 'Mapel Pilihan MP', 'Tutut Sriatin, S.Pd'],
                ['XI MP 3', 'Jumat', 2, 3, 'Sejarah', 'Dra. Anik Indriani'],
                ['XI MP 3', 'Jumat', 4, 5, 'Bahasa Jawa', 'Rizki Putri Wulandari, S.Pd'],
                ['XI MP 3', 'Jumat', 8, 10, 'Konsentrasi MP', 'Titik Samsistini, S.Pd'],
                ['XI MP 3', 'Jumat', 11, 13, 'Bahasa Inggris', 'Andri Retno Yuli Astuti, S.Pd'],
                ['XI MP 4', 'Senin', 2, 5, 'Konsentrasi MP', 'Mega Mahardika, S.Pd'],
                ['XI MP 4', 'Senin', 6, 7, 'BK', 'Veronica Damay Rulitasari, S.Pd'],
                ['XI MP 4', 'Senin', 8, 13, 'Matematika', 'Rulik Indrawati, S.Pd'],
                ['XI MP 4', 'Selasa', 1, 4, 'Konsentrasi MP', 'Mega Mahardika, S.Pd'],
                ['XI MP 4', 'Selasa', 5, 6, 'Sejarah', 'Dra. Anik Indriani'],
                ['XI MP 4', 'Selasa', 7, 8, 'Bahasa Inggris', 'Muto\'atul Khosi\'ah, S.Pd'],
                ['XI MP 4', 'Selasa', 9, 13, 'Bahasa Jawa', 'Rizki Putri Wulandari, S.Pd'],
                ['XI MP 4', 'Rabu', 1, 2, 'Bahasa Inggris', 'Muto\'atul Khosi\'ah, S.Pd'],
                ['XI MP 4', 'Rabu', 6, 7, 'PJOK', 'Zainul Arifin,S.Pd'],
                ['XI MP 4', 'Rabu', 8, 13, 'Konsentrasi MP', 'Mega Mahardika, S.Pd'],
                ['XI MP 4', 'Kamis', 1, 3, 'Konsentrasi MP', 'Mega Mahardika, S.Pd'],
                ['XI MP 4', 'Kamis', 4, 5, 'Mapel Pilihan MP', 'Tutut Sriatin, S.Pd'],
                ['XI MP 4', 'Kamis', 6, 7, 'Bahasa Jepang', 'Sulistyowati, SS'],
                ['XI MP 4', 'Kamis', 8, 13, 'Pendidikan Agama Islam dan Budi Pekerti', 'Alfinu Farikh Abdillah, S.Pd.I'],
                ['XI MP 4', 'Jumat', 2, 3, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['XI MP 4', 'Jumat', 6, 7, 'Konsentrasi MP', 'Mega Mahardika, S.Pd'],
                ['XI MP 4', 'Jumat', 8, 10, 'Bahasa Indonesia', 'Endang Safitri, S.Pd'],
                ['XI MP 4', 'Jumat', 11, 13, 'Konsentrasi MP', 'Mega Mahardika, S.Pd'],
                ['XI AK 1', 'Senin', 2, 3, 'Konsentrasi AK', 'Kasmi, S.Pd., M.Pd'],
                ['XI AK 1', 'Senin', 4, 5, 'Sejarah', 'Dra. Anik Indriani'],
                ['XI AK 1', 'Senin', 6, 8, 'Matematika', 'Eko Saputro, S.Pd'],
                ['XI AK 1', 'Senin', 9, 13, 'Bahasa Jawa', 'Muhammad Fajar Assidiqi, S.Pd'],
                ['XI AK 1', 'Selasa', 1, 2, 'PJOK', 'Agus Fahruddy, S.Pd., M.Pd'],
                ['XI AK 1', 'Selasa', 3, 4, 'BK', 'Astra Bella Flamboyan, S.Psi'],
                ['XI AK 1', 'Selasa', 5, 13, 'Konsentrasi AK', 'Indayah, S.Pd., M.Pd'],
                ['XI AK 1', 'Rabu', 1, 2, 'Bahasa Inggris', 'Agus Muharyanto, M.Pd'],
                ['XI AK 1', 'Rabu', 3, 4, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['XI AK 1', 'Rabu', 5, 6, 'Bahasa Jepang', 'Sulistyowati, SS'],
                ['XI AK 1', 'Rabu', 7, 13, 'Konsentrasi AK', 'Septiani, S.Pd.,M.Pd'],
                ['XI AK 1', 'Kamis', 1, 3, 'Pendidikan Agama Islam dan Budi Pekerti', 'Alfinu Farikh Abdillah, S.Pd.I'],
                ['XI AK 1', 'Kamis', 4, 5, 'Konsentrasi AK', 'Agustina Mardika Rini, S.Pd.,M.Pd'],
                ['XI AK 1', 'Jumat', 2, 3, 'Bahasa Inggris', 'Agus Muharyanto, M.Pd'],
                ['XI AK 1', 'Jumat', 4, 7, 'Konsentrasi AK', 'Dyah Esti Rahayu, S.Pd'],
                ['XI AK 1', 'Jumat', 8, 10, 'Bahasa Indonesia', 'Winartin, S.Pd'],
                ['XI AK 1', 'Jumat', 11, 13, 'Mapel Pilihan AK', 'Yuli Ratnasari, S.Pd'],
                ['XI AK 2', 'Senin', 2, 5, 'Konsentrasi AK', 'Dyah Esti Rahayu, S.Pd'],
                ['XI AK 2', 'Senin', 6, 8, 'Pendidikan Agama Islam dan Budi Pekerti', 'Alfinu Farikh Abdillah, S.Pd.I'],
                ['XI AK 2', 'Senin', 9, 13, 'Bahasa Jepang', 'Sulistyowati, SS'],
                ['XI AK 2', 'Selasa', 1, 2, 'Sejarah', 'Dra. Anik Indriani'],
                ['XI AK 2', 'Selasa', 3, 4, 'PJOK', 'Agus Fahruddy, S.Pd., M.Pd'],
                ['XI AK 2', 'Selasa', 5, 6, 'Mapel Pilihan AK', 'Yuli Ratnasari, S.Pd'],
                ['XI AK 2', 'Selasa', 7, 13, 'Konsentrasi AK', 'Yuli Ratnasari, S.Pd'],
                ['XI AK 2', 'Rabu', 1, 6, 'Konsentrasi AK', 'Pipit Ambarwati, S.Pd'],
                ['XI AK 2', 'Rabu', 7, 8, 'Bahasa Inggris', 'Agus Muharyanto, M.Pd'],
                ['XI AK 2', 'Rabu', 9, 13, 'Bahasa Jawa', 'Muhammad Fajar Assidiqi, S.Pd'],
                ['XI AK 2', 'Kamis', 6, 8, 'Bahasa Indonesia', 'Winartin, S.Pd'],
                ['XI AK 2', 'Kamis', 9, 13, 'Konsentrasi AK', 'Setiyo Winarko, S.Pd'],
                ['XI AK 2', 'Jumat', 2, 3, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['XI AK 2', 'Jumat', 4, 6, 'Matematika', 'Ajeng Okvitasari, S.Pd'],
                ['XI AK 2', 'Jumat', 7, 8, 'Bahasa Inggris', 'Agus Muharyanto, M.Pd'],
                ['XI AK 2', 'Jumat', 9, 10, 'Konsentrasi AK', 'Kasmi, S.Pd., M.Pd'],
                ['XI AK 2', 'Jumat', 11, 13, 'BK', 'Winarsih, S.Pd, M.Pd'],
                ['XI AK 3', 'Senin', 2, 4, 'Pendidikan Agama Islam dan Budi Pekerti', 'Alfinu Farikh Abdillah, S.Pd.I'],
                ['XI AK 3', 'Senin', 5, 6, 'PJOK', 'Agus Fahruddy, S.Pd., M.Pd'],
                ['XI AK 3', 'Senin', 7, 13, 'Konsentrasi AK', 'Atih Wilupi, S.E, M.Pd'],
                ['XI AK 3', 'Selasa', 1, 3, 'Bahasa Indonesia', 'Winartin, S.Pd'],
                ['XI AK 3', 'Selasa', 9, 13, 'Konsentrasi AK', 'Setiyo Winarko, S.Pd'],
                ['XI AK 3', 'Rabu', 1, 6, 'Konsentrasi AK', 'Atih Wilupi, S.E, M.Pd'],
                ['XI AK 3', 'Rabu', 7, 8, 'Mapel Pilihan AK', 'Yuli Ratnasari, S.Pd'],
                ['XI AK 3', 'Rabu', 9, 13, 'Bahasa Jawa', 'Rizki Putri Wulandari, S.Pd'],
                ['XI AK 3', 'Kamis', 1, 2, 'Sejarah', 'Dra. Anik Indriani'],
                ['XI AK 3', 'Kamis', 3, 4, 'Bahasa Jepang', 'Sulistyowati, SS'],
                ['XI AK 3', 'Kamis', 5, 8, 'Konsentrasi AK', 'Dyah Esti Rahayu, S.Pd'],
                ['XI AK 3', 'Kamis', 9, 13, 'Bahasa Inggris', 'Andri Retno Yuli Astuti, S.Pd'],
                ['XI AK 3', 'Jumat', 2, 4, 'Matematika', 'Arvia Rienetasary, S.Pd'],
                ['XI AK 3', 'Jumat', 5, 6, 'Konsentrasi AK', 'Indayah, S.Pd., M.Pd'],
                ['XI AK 3', 'Jumat', 7, 8, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['XI AK 3', 'Jumat', 9, 10, 'Bahasa Inggris', 'Andri Retno Yuli Astuti, S.Pd'],
                ['XI AK 3', 'Jumat', 11, 13, 'BK', 'Nur Eko Wahyuningsih, S.Pd'],
                ['XI AK 4', 'Senin', 7, 8, 'Bahasa Jepang', 'Sulistyowati, SS'],
                ['XI AK 4', 'Senin', 9, 13, 'Bahasa Inggris', 'Andri Retno Yuli Astuti, S.Pd'],
                ['XI AK 4', 'Selasa', 1, 2, 'Mapel Pilihan AK', 'Yuli Ratnasari, S.Pd'],
                ['XI AK 4', 'Selasa', 3, 4, 'Sejarah', 'Dra. Anik Indriani'],
                ['XI AK 4', 'Selasa', 5, 6, 'BK', 'Nur Eko Wahyuningsih, S.Pd'],
                ['XI AK 4', 'Selasa', 7, 13, 'Konsentrasi AK', 'Atih Wilupi, S.E, M.Pd'],
                ['XI AK 4', 'Rabu', 1, 2, 'Bahasa Jawa', 'Rizki Putri Wulandari, S.Pd'],
                ['XI AK 4', 'Rabu', 3, 4, 'Bahasa Inggris', 'Andri Retno Yuli Astuti, S.Pd'],
                ['XI AK 4', 'Rabu', 5, 6, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['XI AK 4', 'Rabu', 7, 8, 'Konsentrasi AK', 'Ninik Sriwidayati, S.Pd., M.Pd'],
                ['XI AK 4', 'Rabu', 9, 13, 'Konsentrasi AK', 'Indayah, S.Pd., M.Pd'],
                ['XI AK 4', 'Kamis', 1, 4, 'Konsentrasi AK', 'Titin Sukmasari, S.Pd., M.Pd'],
                ['XI AK 4', 'Kamis', 5, 7, 'Bahasa Indonesia', 'Siti Khoiriyah, S.Pd'],
                ['XI AK 4', 'Kamis', 8, 13, 'Matematika', 'Basuki Sarjono, S.Pd'],
                ['XI AK 4', 'Jumat', 2, 3, 'PJOK', 'Agus Fahruddy, S.Pd., M.Pd'],
                ['XI AK 4', 'Jumat', 4, 9, 'Konsentrasi AK', 'Septiani, S.Pd.,M.Pd'],
                ['XI AK 4', 'Jumat', 10, 13, 'Pendidikan Agama Islam dan Budi Pekerti', 'Muashofah, M.Pd'],
                ['XI ULW', 'Senin', 2, 4, 'Bahasa Indonesia', 'Purwati,S.Pd'],
                ['XI ULW', 'Senin', 5, 8, 'Konsentrasi ULW', 'Risqi Nur Imama, S.Tr.Par'],
                ['XI ULW', 'Senin', 9, 13, 'Bahasa Inggris', 'Fitria Renytasari, S.Pd'],
                ['XI ULW', 'Selasa', 1, 2, 'Bahasa Inggris', 'Fitria Renytasari, S.Pd'],
                ['XI ULW', 'Selasa', 3, 6, 'Konsentrasi ULW', 'Risqi Nur Imama, S.Tr.Par'],
                ['XI ULW', 'Selasa', 9, 13, 'Sejarah', 'Erna Qoriah, S.E.'],
                ['XI ULW', 'Rabu', 1, 2, 'Bahasa Jepang', 'Sulistyowati, SS'],
                ['XI ULW', 'Rabu', 6, 8, 'Konsentrasi ULW', 'Nur Nastutisari, S.ST.Par.'],
                ['XI ULW', 'Rabu', 9, 13, 'Bahasa Jawa', 'Ajeng Okvitasari, S.Pd'],
                ['XI ULW', 'Kamis', 1, 2, 'PJOK', 'Bella Prakoso, S.Pd'],
                ['XI ULW', 'Kamis', 3, 5, 'Matematika', 'Dwi Nova Setyandari, S.Pd'],
                ['XI ULW', 'Kamis', 6, 8, 'Konsentrasi ULW', 'Nur Nastutisari, S.ST.Par.'],
                ['XI ULW', 'Kamis', 9, 13, 'Bahasa Jepang', 'Sulistyowati, SS'],
                ['XI ULW', 'Jumat', 2, 4, 'Pendidikan Agama Islam dan Budi Pekerti', 'Muashofah, M.Pd'],
                ['XI ULW', 'Jumat', 5, 8, 'Konsentrasi ULW', 'Risqi Nur Imama, S.Tr.Par'],
                ['XI ULW', 'Jumat', 9, 10, 'BK', 'Niken Hari Pratiwi, S.Psi., M.Pd'],
                ['XI ULW', 'Jumat', 11, 13, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['XI DKV 1', 'Senin', 2, 3, 'Bahasa Inggris', 'Fajar Wahyu Pratiwi, S.S'],
                ['XI DKV 1', 'Senin', 4, 6, 'Konsentrasi DKV', 'Danang Anjar Hymawanto, S.Pd'],
                ['XI DKV 1', 'Senin', 7, 13, 'Konsentrasi DKV', 'Istiana Suhartati, S.T'],
                ['XI DKV 1', 'Selasa', 1, 3, 'Konsentrasi DKV', 'Agus Pramono, S.Sn'],
                ['XI DKV 1', 'Selasa', 4, 6, 'Konsentrasi DKV', 'Khoyrotun Hisani, S.Sn'],
                ['XI DKV 1', 'Selasa', 9, 13, 'Sejarah', 'Indriati, S.Pd'],
                ['XI DKV 1', 'Rabu', 1, 2, 'BK', 'Astra Bella Flamboyan, S.Psi'],
                ['XI DKV 1', 'Rabu', 3, 5, 'Konsentrasi DKV', 'Khoyrotun Hisani, S.Sn'],
                ['XI DKV 1', 'Rabu', 6, 7, 'Konsentrasi DKV', 'Danang Anjar Hymawanto, S.Pd'],
                ['XI DKV 1', 'Kamis', 1, 2, 'PJOK', 'Ilham Sungeidi, S.Pd'],
                ['XI DKV 1', 'Kamis', 3, 4, 'Bahasa Jawa', 'Khoyrotun Hisani, S.Sn'],
                ['XI DKV 1', 'Kamis', 5, 7, 'Bahasa Indonesia', 'Endang Safitri, S.Pd'],
                ['XI DKV 1', 'Kamis', 8, 13, 'Matematika', 'Elysa Yuli Nur\'aini, S.Si'],
                ['XI DKV 1', 'Jumat', 2, 5, 'Mapel Pilihan DKV', 'Endik Kuswantoro, S.Kom.,M.T'],
                ['XI DKV 1', 'Jumat', 6, 7, 'Bahasa Inggris', 'Fajar Wahyu Pratiwi, S.S'],
                ['XI DKV 1', 'Jumat', 8, 10, 'Pendidikan Agama Islam dan Budi Pekerti', 'Sinta Lestari, S.Pd.I'],
                ['XI DKV 1', 'Jumat', 11, 13, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['XI DKV 2', 'Senin', 2, 3, 'BK', 'Astra Bella Flamboyan, S.Psi'],
                ['XI DKV 2', 'Senin', 4, 6, 'Konsentrasi DKV', 'Khoyrotun Hisani, S.Sn'],
                ['XI DKV 2', 'Senin', 7, 8, 'Bahasa Jawa', 'Khoyrotun Hisani, S.Sn'],
                ['XI DKV 2', 'Senin', 9, 13, 'Pendidikan Pancasila', 'Abdul Rohman, S.Pd'],
                ['XI DKV 2', 'Selasa', 1, 3, 'Konsentrasi DKV', 'Khoyrotun Hisani, S.Sn'],
                ['XI DKV 2', 'Selasa', 4, 7, 'Konsentrasi DKV', 'Istiana Suhartati, S.T'],
                ['XI DKV 2', 'Selasa', 8, 13, 'Konsentrasi DKV', 'Danang Anjar Hymawanto, S.Pd'],
                ['XI DKV 2', 'Rabu', 1, 2, 'Konsentrasi DKV', 'Danang Anjar Hymawanto, S.Pd'],
                ['XI DKV 2', 'Rabu', 3, 5, 'Bahasa Indonesia', 'Endang Safitri, S.Pd'],
                ['XI DKV 2', 'Rabu', 6, 7, 'PJOK', 'Ilham Sungeidi, S.Pd'],
                ['XI DKV 2', 'Rabu', 8, 13, 'Matematika', 'Elysa Yuli Nur\'aini, S.Si'],
                ['XI DKV 2', 'Kamis', 4, 5, 'Sejarah', 'Indriati, S.Pd'],
                ['XI DKV 2', 'Kamis', 6, 7, 'Bahasa Inggris', 'Fajar Wahyu Pratiwi, S.S'],
                ['XI DKV 2', 'Kamis', 8, 13, 'Pendidikan Agama Islam dan Budi Pekerti', 'Sinta Lestari, S.Pd.I'],
                ['XI DKV 2', 'Jumat', 4, 5, 'Bahasa Inggris', 'Fajar Wahyu Pratiwi, S.S'],
                ['XI DKV 2', 'Jumat', 6, 9, 'Mapel Pilihan DKV', 'Endik Kuswantoro, S.Kom.,M.T'],
                ['XI DKV 2', 'Jumat', 10, 13, 'Konsentrasi DKV', 'Agus Pramono, S.Sn'],
                ['XI PSPT 1', 'Senin', 2, 4, 'Bahasa Indonesia', 'Umi Kulsum, S.Pd'],
                ['XI PSPT 1', 'Senin', 5, 6, 'Konsentrasi PSPT', 'Benny Mamora, S.Kom'],
                ['XI PSPT 1', 'Senin', 7, 13, 'Konsentrasi PSPT', 'Joko Priyanto, S.Kom'],
                ['XI PSPT 1', 'Selasa', 1, 2, 'Konsentrasi PSPT', 'Sa\'ad Wazis Hiedayat, S.Pd'],
                ['XI PSPT 1', 'Selasa', 3, 4, 'Konsentrasi PSPT', 'Sa\'ad Wazis Hiedayat, S.Pd'],
                ['XI PSPT 1', 'Selasa', 5, 6, 'Konsentrasi PSPT', 'Joko Priyanto, S.Kom'],
                ['XI PSPT 1', 'Selasa', 7, 8, 'Konsentrasi PSPT', 'Joko Priyanto, S.Kom'],
                ['XI PSPT 1', 'Selasa', 9, 13, 'BK', 'Winarsih, S.Pd, M.Pd'],
                ['XI PSPT 1', 'Rabu', 1, 4, 'Konsentrasi PSPT', 'Tuhu Eries Kudori, S.Sn'],
                ['XI PSPT 1', 'Rabu', 5, 6, 'Bahasa Inggris', 'Fajar Wahyu Pratiwi, S.S'],
                ['XI PSPT 1', 'Rabu', 7, 8, 'Pendidikan Pancasila', 'Fitri Amaliyah, S.Pd'],
                ['XI PSPT 1', 'Kamis', 1, 4, 'Mapel Pilihan PSPT', 'Tuhu Eries Kudori, S.Sn'],
                ['XI PSPT 1', 'Kamis', 5, 7, 'Pendidikan Agama Islam dan Budi Pekerti', 'Dra. Hanik Pangestuti'],
                ['XI PSPT 1', 'Kamis', 8, 13, 'Matematika', 'Ajeng Okvitasari, S.Pd'],
                ['XI PSPT 1', 'Jumat', 2, 3, 'Bahasa Inggris', 'Fajar Wahyu Pratiwi, S.S'],
                ['XI PSPT 1', 'Jumat', 4, 5, 'Sejarah', 'Dra. Anik Indriani'],
                ['XI PSPT 1', 'Jumat', 6, 7, 'PJOK', 'Bella Prakoso, S.Pd'],
                ['XI PSPT 1', 'Jumat', 8, 9, 'Bahasa Jawa', 'Erna Qoriah, S.E.'],
                ['XI PSPT 2', 'Senin', 2, 4, 'Matematika', 'Eko Saputro, S.Pd'],
                ['XI PSPT 2', 'Senin', 7, 13, 'Konsentrasi PSPT', 'Tuhu Eries Kudori, S.Sn'],
                ['XI PSPT 2', 'Selasa', 1, 3, 'Pendidikan Agama Islam dan Budi Pekerti', 'Dra. Hanik Pangestuti'],
                ['XI PSPT 2', 'Selasa', 7, 8, 'Sejarah', 'Dra. Anik Indriani'],
                ['XI PSPT 2', 'Selasa', 9, 13, 'Bahasa Inggris', 'Muto\'atul Khosi\'ah, S.Pd'],
                ['XI PSPT 2', 'Rabu', 1, 4, 'Konsentrasi PSPT', 'Joko Priyanto, S.Kom'],
                ['XI PSPT 2', 'Rabu', 5, 8, 'Mapel Pilihan PSPT', 'Tuhu Eries Kudori, S.Sn'],
                ['XI PSPT 2', 'Rabu', 9, 13, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['XI PSPT 2', 'Kamis', 1, 2, 'Konsentrasi PSPT', 'Joko Priyanto, S.Kom'],
                ['XI PSPT 2', 'Kamis', 3, 4, 'Konsentrasi PSPT', 'Joko Priyanto, S.Kom'],
                ['XI PSPT 2', 'Kamis', 5, 6, 'Konsentrasi PSPT', 'Sa\'ad Wazis Hiedayat, S.Pd'],
                ['XI PSPT 2', 'Kamis', 7, 8, 'Konsentrasi PSPT', 'Sa\'ad Wazis Hiedayat, S.Pd'],
                ['XI PSPT 2', 'Kamis', 9, 13, 'Konsentrasi PSPT', 'Benny Mamora, S.Kom'],
                ['XI PSPT 2', 'Jumat', 2, 3, 'PJOK', 'Bella Prakoso, S.Pd'],
                ['XI PSPT 2', 'Jumat', 4, 5, 'BK', 'Winarsih, S.Pd, M.Pd'],
                ['XI PSPT 2', 'Jumat', 6, 8, 'Bahasa Indonesia', 'Umi Kulsum, S.Pd'],
                ['XI PSPT 2', 'Jumat', 9, 10, 'Bahasa Inggris', 'Muto\'atul Khosi\'ah, S.Pd'],
                ['XI PSPT 2', 'Jumat', 11, 13, 'Bahasa Jawa', 'Erna Qoriah, S.E.'],
                ['XI AN 1', 'Senin', 2, 4, 'Bahasa Indonesia', 'Arif Setyobudi, S.Pd'],
                ['XI AN 1', 'Senin', 5, 6, 'Bahasa Inggris', 'Agus Muharyanto, M.Pd'],
                ['XI AN 1', 'Senin', 7, 8, 'Konsentrasi AN', 'Andika Christian Sasmita, S.ST'],
                ['XI AN 1', 'Senin', 9, 13, 'Mapel Pilihan AN', 'Endik Kuswantoro, S.Kom.,M.T'],
                ['XI AN 1', 'Selasa', 1, 3, 'Konsentrasi AN', 'Erwan Septiyono, S.Pd'],
                ['XI AN 1', 'Selasa', 4, 7, 'Konsentrasi AN', 'Rika Okta Maulida, S.Ds.'],
                ['XI AN 1', 'Selasa', 8, 13, 'Konsentrasi AN', 'Dhuana Putri Puspitasary, S.Pd'],
                ['XI AN 1', 'Rabu', 1, 3, 'Konsentrasi AN', 'Endik Kuswantoro, S.Kom.,M.T'],
                ['XI AN 1', 'Rabu', 7, 8, 'Sejarah', 'Yustin Febrini, S.Pd'],
                ['XI AN 1', 'Rabu', 9, 13, 'Pendidikan Pancasila', 'Khuriyatul Kamila, S.Si'],
                ['XI AN 1', 'Kamis', 1, 3, 'Konsentrasi AN', 'Erwan Septiyono, S.Pd'],
                ['XI AN 1', 'Kamis', 6, 8, 'Pendidikan Agama Islam dan Budi Pekerti', 'Muashofah, M.Pd'],
                ['XI AN 1', 'Kamis', 9, 13, 'Bahasa Inggris', 'Agus Muharyanto, M.Pd'],
                ['XI AN 1', 'Jumat', 2, 3, 'Mapel Pilihan AN', 'Andika Christian Sasmita, S.ST'],
                ['XI AN 1', 'Jumat', 4, 5, 'PJOK', 'Bella Prakoso, S.Pd'],
                ['XI AN 1', 'Jumat', 6, 8, 'Matematika', 'Dwi Nova Setyandari, S.Pd'],
                ['XI AN 1', 'Jumat', 9, 10, 'BK', 'Siti Maisaroh, S.Pd'],
                ['XI AN 1', 'Jumat', 11, 13, 'Bahasa Jawa', 'Ajeng Okvitasari, S.Pd'],
                ['XI AN 2', 'Senin', 2, 4, 'Konsentrasi AN', 'Dhuana Putri Puspitasary, S.Pd'],
                ['XI AN 2', 'Senin', 5, 8, 'Konsentrasi AN', 'Rika Okta Maulida, S.Ds.'],
                ['XI AN 2', 'Senin', 9, 13, 'Konsentrasi AN', 'Andika Christian Sasmita, S.ST'],
                ['XI AN 2', 'Selasa', 4, 5, 'Mapel Pilihan AN', 'Endik Kuswantoro, S.Kom.,M.T'],
                ['XI AN 2', 'Selasa', 6, 7, 'Bahasa Inggris', 'Agus Muharyanto, M.Pd'],
                ['XI AN 2', 'Selasa', 8, 13, 'Bahasa Indonesia', 'Arif Setyobudi, S.Pd'],
                ['XI AN 2', 'Rabu', 1, 2, 'Bahasa Jawa', 'Luluk Munfarida,S.Pd'],
                ['XI AN 2', 'Rabu', 3, 4, 'PJOK', 'Bella Prakoso, S.Pd'],
                ['XI AN 2', 'Rabu', 5, 7, 'Konsentrasi AN', 'Endik Kuswantoro, S.Kom.,M.T'],
                ['XI AN 2', 'Rabu', 8, 13, 'Konsentrasi AN', 'Erwan Septiyono, S.Pd'],
                ['XI AN 2', 'Kamis', 1, 2, 'BK', 'Siti Maisaroh, S.Pd'],
                ['XI AN 2', 'Kamis', 3, 5, 'Pendidikan Agama Islam dan Budi Pekerti', 'Muashofah, M.Pd'],
                ['XI AN 2', 'Kamis', 6, 8, 'Matematika', 'Dwi Nova Setyandari, S.Pd'],
                ['XI AN 2', 'Kamis', 9, 13, 'Sejarah', 'Yustin Febrini, S.Pd'],
                ['XI AN 2', 'Jumat', 2, 4, 'Konsentrasi AN', 'Erwan Septiyono, S.Pd'],
                ['XI AN 2', 'Jumat', 5, 6, 'Mapel Pilihan AN', 'Andika Christian Sasmita, S.ST'],
                ['XI AN 2', 'Jumat', 9, 10, 'Pendidikan Pancasila', 'Wiwik Yuniarsih, S.Pd'],
                ['XI AN 2', 'Jumat', 11, 13, 'Bahasa Inggris', 'Agus Muharyanto, M.Pd'],
            ];

            $inserted = 0;
            $createdGuru = [];

            foreach ($rows as [$namaKelas, $hari, $jamMulai, $jamSelesai, $namaMapel, $namaGuru]) {
                $guruKey = $normal($namaGuru);

                if (! isset($guru[$guruKey])) {
                    // Cari guru yang sudah ada berdasarkan kemiripan nama
                    $cleanTarget = strtolower(preg_replace('/[^a-z0-9]/', '', explode(',', $namaGuru)[0]));
                    $matchedUser = null;
                    foreach (User::where('role', 'guru')->get() as $u) {
                        $cleanU = strtolower(preg_replace('/[^a-z0-9]/', '', explode(',', $u->name)[0]));
                        if ($cleanTarget !== '' && ($cleanTarget === $cleanU || str_contains($cleanU, $cleanTarget) || str_contains($cleanTarget, $cleanU))) {
                            $matchedUser = $u;
                            break;
                        }
                    }

                    if ($matchedUser) {
                        $guru[$guruKey] = $matchedUser->id;
                    } else {
                        $username = $guruKey ?: 'guru'.(count($guru) + 1);
                        $baseUsername = $username;
                        $suffix = 1;
                        while (User::where('username', $username)->exists()) {
                            $username = $baseUsername.$suffix++;
                        }

                        $email = $username.'@jurnalkita.local';
                        $emailSuffix = 1;
                        while (User::where('email', $email)->exists()) {
                            $email = $username.($emailSuffix++).'@jurnalkita.local';
                        }

                        $newGuru = User::create([
                            'name' => $namaGuru,
                            'username' => $username,
                            'nip' => null,
                            'email' => $email,
                            'password' => Hash::make('guru123'),
                            'role' => 'guru',
                        ]);

                        $guru[$guruKey] = $newGuru->id;
                        $createdGuru[$namaGuru] = true;
                    }
                }

                if (! isset($kelas[$namaKelas])) {
                    throw new \RuntimeException("Kelas tidak ditemukan: {$namaKelas}");
                }

                if (! isset($mapel[$namaMapel])) {
                    throw new \RuntimeException("Mapel tidak ditemukan: {$namaMapel}");
                }

                // Normalisasi batas jam pelajaran sesuai jadwal KBM resmi:
                // - Senin s.d. Kamis: jam ke-1 s.d. 10
                // - Jumat Kelas XI: jam ke-1 s.d. 12
                // - Jumat Kelas X: jam ke-1 s.d. 13
                if (in_array($hari, ['Senin', 'Selasa', 'Rabu', 'Kamis']) && $jamSelesai > 10) {
                    $jamSelesai = 10;
                } elseif ($hari === 'Jumat' && str_starts_with($namaKelas, 'XI') && $jamSelesai > 12) {
                    $jamSelesai = 12;
                } elseif ($hari === 'Jumat' && $jamSelesai > 13) {
                    $jamSelesai = 13;
                }

                JadwalMengajar::create([
                    'id_user' => $guru[$guruKey],
                    'id_kelas' => $kelas[$namaKelas],
                    'id_mapel' => $mapel[$namaMapel],
                    'hari' => $hari,
                    'jam_mulai' => $jamMulai,
                    'jam_selesai' => $jamSelesai,
                ]);

                $inserted++;
            }

            $this->command->info("Jadwal berhasil dimasukkan: {$inserted} baris.");

            if ($createdGuru) {
                $this->command->warn(
                    'Guru baru yang dibuat: '.count($createdGuru).' akun. Password awal: guru123'
                );
            }
        });
    }
}
